// <auto-generated>
// GENERATED from RDPMS_cause_code_attid_map.xlsx by gen_rdpms_maps.py.
// DO NOT EDIT BY HAND. Edit the xlsx (the source of truth) and re-run the converter.
// Source: RDSO/SPN/257/2025 v2.0 + EdgeX PM doc + SensorHealth_Rules.json
// </auto-generated>
using System;
using System.Collections.Generic;

namespace E7MRIWeb.Areas.FRS25.Controllers
{
    public static class RdpmsMaps
    {
        // STAGE 1: alias (normalized: unit-stripped, ws-collapsed, upper) -> Title. All asset types.
        // 196 entries.
        public static readonly Dictionary<string, string> AliasToTitle =
            new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "ITC FEED END", "If mA" },   // Track Circuit
            { "ITC RELAY END", "Ir mA" },   // Track Circuit
            { "VTC RELAY END", "Vr" },   // Track Circuit
            { "VTC CH FEED END", "Choke V" },   // Track Circuit
            { "ITC TFC O/P", "Charger mA" },   // Track Circuit
            { "VTC 24 DC TPR I/P", "TPR V" },   // Track Circuit
            { "VTC FEED END", "Vf" },   // Track Circuit
            { "VTC TFC I/P", "Charger V" },   // Track Circuit
            { "VTC TFC O/P", "Charger OP V" },   // Track Circuit
            { "VTC 24 DC LOC", "TPR V (Loc)" },   // Track Circuit
            { "VTC TR", "TR V (Relay)" },   // Track Circuit
            { "ITC BATT CHARG", "ITC BATT CHARG" },   // Track Circuit
            { "VTC VAR RES", "VTC VAR RES" },   // Track Circuit
            { "RTC CH FEED END", "RTC CH FEED END" },   // Track Circuit
            { "RTC VAR RES", "RTC VAR RES" },   // Track Circuit
            { "RTC CH RELAY END", "RTC CH RELAY END" },   // Track Circuit
            { "RRAIL", "RRAIL" },   // Track Circuit
            { "VTC CH RELAY END", "VTC CH RELAY END" },   // Track Circuit
            { "IBALST", "IBlAST" },   // Track Circuit
            { "IBLAST", "IBLAST" },   // Track Circuit
            { "VSIG RG", "RG V" },   // Signal
            { "ISIG RG", "RG mA" },   // Signal
            { "VSIG DG", "DG V" },   // Signal
            { "ISIG DG", "DG mA" },   // Signal
            { "VSIG HG", "HG V" },   // Signal
            { "ISIG HG", "HG mA" },   // Signal
            { "VSIG HHG", "HHG V" },   // Signal
            { "ISIG HHG", "HHG mA" },   // Signal
            { "VSHSIG ON", "On Aspect V" },   // Signal
            { "ISHSIG ON", "On Aspect mA" },   // Signal
            { "VSHSIG OFF", "Off Aspect V" },   // Signal
            { "ISHSIG OFF", "Off Aspect mA" },   // Signal
            { "AUG V", "UGA V" },   // Signal
            { "IROSIG (BUG)", "BUG mA" },   // Signal
            { "VSIG HHPR", "HHPR" },   // Signal
            { "VSIG DPR", "DPR" },   // Signal
            { "VSIG HPR", "HPR" },   // Signal
            { "VROSIG HPR (BUPR)", "BUPR" },   // Signal
            { "IROSIG (CUG)", "CUG mA" },   // Signal
            { "VROSIG HPR (CUPR)", "CUPR" },   // Signal
            { "ISHSIG PILOT", "PILOT mA" },   // Signal
            { "IROSIG (AUG)", "AUG mA" },   // Signal
            { "IROSIG (DUG)", "DUG mA" },   // Signal
            { "IROSIG (EUG)", "EUG mA" },   // Signal
            { "VROSIG (AUG)", "AUG V" },   // Signal
            { "VSHSIG PILOT", "PILOT V" },   // Signal
            { "VROSIG (BUG)", "BUG V" },   // Signal
            { "VROSIG (CUG)", "CUG V" },   // Signal
            { "VROSIG HPR (AUPR)", "AUPR" },   // Signal
            { "VROSIG (DUG)", "DUG V" },   // Signal
            { "VROSIG HPR (DUPR)", "DUPR" },   // Signal
            { "VROSIG HPR (EUPR)", "EUPR" },   // Signal
            { "ICOSIG", "Co_Hg mA" },   // Signal
            { "VCOSIG", "Co_Hg V" },   // Signal
            { "VCOSIG HPR", "Co_HPR" },   // Signal
            { "VROSIG (EUG)", "EUG V" },   // Signal
            { "VSHSIG HPR", "Sh-HPR" },   // Signal
            { "VROSIG", "VRoSig" },   // Signal
            { "IROSIG", "IRoSig" },   // Signal
            { "VROSIG HPR", "VRoSig HPR" },   // Signal
            { "A VPT NWKR", "A End - NWKR" },   // Point Machine
            { "A VPT RWKR", "A End - RWKR" },   // Point Machine
            { "B VPT NWKR", "B End - NWKR" },   // Point Machine
            { "B VPT RWKR", "B End - RWKR" },   // Point Machine
            { "B VPT 110 DC LOC N", "B End - NW-V" },   // Point Machine
            { "B IPT N", "B End - NW-C" },   // Point Machine
            { "B VPT 110 DC LOC R", "B End - RW-V" },   // Point Machine
            { "B IPT R", "B End - RW-C" },   // Point Machine
            { "A VPT 110 DC LOC N", "A End - NW-V" },   // Point Machine
            { "A IPT N", "A End - NW-C" },   // Point Machine
            { "A VPT110 DC LOC R", "A End - RW-V" },   // Point Machine
            { "A IPT R", "A End - RW-C" },   // Point Machine
            { "A VPT 24 DC LOC N", "A End - NWKR (Loc)" },   // Point Machine
            { "A VPT 24 DC LOC R", "A End - RWKR (Loc)" },   // Point Machine
            { "B VPT 24 DC LOC N", "B End - NWKR (Loc)" },   // Point Machine
            { "B VPT 24 DC LOC R", "B End - RWKR (Loc)" },   // Point Machine
            { "A TPT N", "A End - NW-T" },   // Point Machine
            { "A TPT R", "A End - RW-T" },   // Point Machine
            { "B TPT N", "B End - NW-T" },   // Point Machine
            { "B TPT R", "B End - RW-T" },   // Point Machine
            { "Y(G)", "Y" },   // Point Machine
            { "Z(G)", "Z" },   // Point Machine
            { "VPT RWKR", "VPT RWKR" },   // Point Machine
            { "VPT 24 DC LOC N", "VPT 24 DC LOC N" },   // Point Machine
            { "IPT N (SIG)", "IPT N (Sig)" },   // Point Machine
            { "TPT N", "TPT N" },   // Point Machine
            { "X(G)", "X" },   // Point Machine
            { "IPT N", "IPT N" },   // Point Machine
            { "IPT R (SIG)", "IPT R (Sig)" },   // Point Machine
            { "IPT R", "IPT R" },   // Point Machine
            { "TPT R", "TPT R" },   // Point Machine
            { "VPT NWKR", "VPT NWKR" },   // Point Machine
            { "VPT 24 DC LOC R", "VPT 24 DC LOC R" },   // Point Machine
            { "VPT 110 DC LOC N", "VPT 110 DC Loc N" },   // Point Machine
            { "VPT 110 DC LOC N (SIG)", "VPT 110 DC Loc N (Sig)" },   // Point Machine
            { "VPT110 DC LOC R", "VPT110 DC Loc R" },   // Point Machine
            { "VPT110 DC LOC R (SIG)", "VPT110 DC Loc R (Sig)" },   // Point Machine
            { "VAXCO EQ", "Power supply of Equipment" },   // 4
            { "IAXCO EQ", "Current of Equipment" },   // 4
            { "VAXCO 24 DC LOC", "24 V DC going to VPR" },   // 4
            { "VAXCO 24 DC VPR I/P", "24 V DC of VPR" },   // 4
            { "VELB-A AC", "V AC at ELB -A Feed going to motor for closing/opening" },   // 5
            { "VELB-B AC", "V AC at ELB -B Feed going to motor for closing/opening" },   // 5
            { "IELB-A AC CLOSE", "ELB-A Closing current" },   // 5
            { "IELB-A AC OPEN", "ELB-A Opening current" },   // 5
            { "IELB-B AC CLOSE", "ELB-B Closing current" },   // 5
            { "IELB-B AC OPEN", "ELB-B Opening current" },   // 5
            { "VELB-A DC", "V AC at ELB -A Feed going to motor for closing/opening" },   // 5
            { "VELB-B DC", "V AC at ELB -B Feed going to motor for closing/opening" },   // 5
            { "IELB-A DC CLOSE", "ELB-A Closing current" },   // 5
            { "IELB-A DC OPEN", "ELB-A Opening current" },   // 5
            { "IELB-B DC CLOSE", "ELB-B Closing current" },   // 5
            { "IELB-B DC OPEN", "ELB-B Opening current" },   // 5
            { "VELB-A CLOSE BUTTON", "ELB-A close Relay voltage" },   // 5
            { "VELB-A CLOSED & LOCKED IND", "ELB -A closed & Locked indication Relay voltage" },   // 5
            { "VELB-B CLOSE BUTTON", "ELB-B close Relay" },   // 5
            { "VELB-B CLOSED & LOCKED IND", "ELB -B closed & Locked indication Relay" },   // 5
            { "VELB FINAL SLOT", "Final Relay for gate closed and locked slot transfer" },   // 5
            { "VELB-A 110 AC OPEN (SIG)", "VELB-A 110 AC OPEN (Sig)" },   // 5
            { "IELB-A CLOSE (SIG)", "IELB-A CLOSE (Sig)" },   // 5
            { "IELB-A OPEN (SIG)", "IELB-A OPEN (Sig)" },   // 5
            { "VELB-A 110 AC CLOSE", "VELB-A 110 AC CLOSE" },   // 5
            { "VELB-A 110 AC CLOSE (SIG)", "VELB-A 110 AC CLOSE (Sig)" },   // 5
            { "IELB-A CLOSE", "IELB-A CLOSE" },   // 5
            { "IELB-A OPEN", "IELB-A OPEN" },   // 5
            { "VELB-A 110 AC OPEN", "VELB-A 110 AC OPEN" },   // 5
            { "TEST", "Test Attribute" },   // 12
            { "VUFSBI EQ", "Power supply of Equipment" },   // 23
            { "IUFSBI EQ", "Current of Equipment" },   // 23
            { "V", "110V DC" },   // IPS
            { "VIPS 110 DC", "IPS 110 DC O/P Voltage" },   // IPS
            { "VIPS SIG-1 110 AC", "IPS 110 AC Sig-1 O/P Voltage" },   // IPS
            { "VIPS SIG-2 110 AC", "IPS 110 AC Sig-2 O/P  Voltage" },   // IPS
            { "VIPS SIG-3 110 AC", "IPS 110 AC Sig-3 O/P  Voltage" },   // IPS
            { "VIPS SIG-4 110 AC", "IPS 110 AC Sig-4 O/P  Voltage" },   // IPS
            { "VIPS TR-1 110 AC", "IPS 110 AC TR-1 O/P  Voltage" },   // IPS
            { "VIPS TR-2 110 AC", "IPS 110 AC TR-2 O/P  Voltage" },   // IPS
            { "VIPS TR-3 110 AC", "IPS 110 AC TR-3 O/P  Voltage" },   // IPS
            { "VIPS TR-4 110 AC", "IPS 110 AC TR-4 O/P  Voltage" },   // IPS
            { "VIPS SMR-1 110 DC", "IPS SMR-1 Voltage" },   // IPS
            { "VIPS SMR-2 110 DC", "IPS SMR-2 Voltage" },   // IPS
            { "VIPS SMR-3 110 DC", "IPS SMR-3 Voltage" },   // IPS
            { "VIPS SMR-4 110 DC", "IPS SMR-4 Voltage" },   // IPS
            { "VIPS SMR-5 110 DC", "IPS SMR-5 Voltage" },   // IPS
            { "VIPS DC R INT", "IPS DC-DC Relay Internal Voltage-1" },   // IPS
            { "VIPS DC R EXT", "IPS DC-DC Relay External Voltage-1" },   // IPS
            { "VIPS DC AXLE C", "IPS DC-DC AXLE COUNTER Voltage-1" },   // IPS
            { "VIPS DC PAN IND", "IPS DC-DC PANEL INDICATION Voltage" },   // IPS
            { "VIPS DC BLOCK LOCAL", "IPS DC-DC BLOCK LOCAL Voltage" },   // IPS
            { "VIPS DC HKT MAG", "IPS DC-DC HKT MAGNETO Voltage" },   // IPS
            { "VIPS DC BLOCK LINE UP", "IPS DC-DC BLOCK LINE UP Voltage" },   // IPS
            { "VIPS DC BLOCK LINE DN", "IPS DC-DC BLOCK LINE DN Voltage" },   // IPS
            { "VIPS DC BLOCK TEL UP", "IPS DC-DC BLOCK TELE UP Voltage" },   // IPS
            { "VIPS DC BLOCK TEL DN", "IPS DC-DC BLOCK TELE DN Voltage" },   // IPS
            { "VIPS DC DATALOG", "IPS DC-DC DATALOGGER Voltage" },   // IPS
            { "VIPS DC EI", "IPS DC-DC EI Voltage" },   // IPS
            { "IIPS BATT CHAR 110 DC", "IPS Batterry charging Current" },   // IPS
            { "VIPS I/P", "IPS input Voltage" },   // IPS
            { "VIPS DC R INT-2", "IPS DC-DC Relay Internal Voltage-2" },   // IPS
            { "VIPS DC R EXT-2", "IPS DC-DC Relay External Voltage-2" },   // IPS
            { "VIPS DC AXLE C-2", "IPS DC-DC AXLE COUNTER Voltage-2" },   // IPS
            { "VIPS DC AXLE C-3", "IPS DC-DC AXLE COUNTER Voltage-3" },   // IPS
            { "VIPS DC AXLE C-4", "IPS DC-DC AXLE COUNTER Voltage-4" },   // IPS
            { "VIPS DC AXLE C-5", "IPS DC-DC AXLE COUNTER Voltage-5" },   // IPS
            { "VIPS DC AXLE C-6", "IPS DC-DC AXLE COUNTER Voltage-6" },   // IPS
            { "VIPS BATT 110 DC", "VIPS Batt 110 DC" },   // IPS
            { "VIPS DC R EXT-5 24DC", "VIPS DC R EXT-5 24DC" },   // IPS
            { "VIPS DC R INT-2 24DC", "VIPS DC R INT-2 24DC" },   // IPS
            { "VIPS DC DATALOG-2 24DC", "VIPS DC DATALOG-2 24DC" },   // IPS
            { "VIPS DC R INT-1 24DC", "VIPS DC R INT-1 24DC" },   // IPS
            { "VIPS DC BLOCK LINE UP-1 24DC", "VIPS DC BLOCK LINE UP-1 24DC" },   // IPS
            { "VIPS DC BLOCK LINE DN-2 24DC", "VIPS DC  BLOCK LINE DN-2 24DC" },   // IPS
            { "VIPS DC AXLE C-1 24DC", "VIPS DC AXLE C-1 24DC" },   // IPS
            { "VIPS DC AXLE C-2 24DC", "VIPS DC AXLE C-2 24DC" },   // IPS
            { "VIPS DC AXLE C-3 24DC", "VIPS DC AXLE C-3 24DC" },   // IPS
            { "VIPS DC R INT-5 24DC", "VIPS DC R INT-5 24DC" },   // IPS
            { "VIPS DC BLOCK TEL 2 6DC", "VIPS DC BLOCK TEL 2 6DC" },   // IPS
            { "VIPS DC BLOCK TEL 1 6DC", "VIPS DC BLOCK TEL 1 6DC" },   // IPS
            { "VIPS DC R INT-3 24DC", "VIPS DC R INT-3 24DC" },   // IPS
            { "VIPS DC R EXT-2 24DC", "VIPS DC R EXT-2 24DC" },   // IPS
            { "VIPS DC R INT-4 24DC", "VIPS DC R INT-4 24DC" },   // IPS
            { "VIPS DC BLOCK LINE DN-1 24DC", "VIPS DC  BLOCK LINE DN-1 24DC" },   // IPS
            { "VIPS DC R EXT-4 24DC", "VIPS DC R EXT-4 24DC" },   // IPS
            { "VIPS DC DATALOG-1 24DC", "VIPS DC DATALOG-1 24DC" },   // IPS
            { "VIPS DC AXLE C-4 24DC", "VIPS DC AXLE C-4 24DC" },   // IPS
            { "VIPS DC PAN-1 IND 24DC", "VIPS DC  PAN-1 IND  24DC" },   // IPS
            { "VIPS DC R EXT-3 24DC", "VIPS DC R EXT-3 24DC" },   // IPS
            { "VIPS DC PAN-2 IND 24DC", "VIPS DC  PAN-2 IND  24DC" },   // IPS
            { "VIPS 220 AC", "VIPS 220 AC" },   // IPS
            { "VIPS DC BLOCK LINE UP-2 24DC", "VIPS DC BLOCK LINE UP-2 24DC" },   // IPS
            { "VIPS DC R EXT-1 24DC", "VIPS DC R EXT-1 24DC" },   // IPS
            { "VIPS BATT BANK 1 DC", "VIPS Batt Bank 1 DC" },   // IPS
            { "VIPS BATT BANK 3 DC", "VIPS Batt Bank 3 DC" },   // IPS
            { "VIPS BATT BANK 2 DC", "VIPS Batt Bank 2 DC" },   // IPS
            { "TEMP1", "TEMP1" },   // 40
            { "HUMD1", "HUMD1" },   // 40
        };

        // STAGE 2: sensor health bands. Key = normalized tag/title. min/max valid band + correlation partners.
        // 64 entries.
        public struct HealthBand { public double Min; public double Max; public string Corr; public string Resolves;
            public HealthBand(double mn, double mx, string corr, string res){ Min=mn; Max=mx; Corr=corr; Resolves=res; } }
        public static readonly Dictionary<string, HealthBand> HealthBands =
            new Dictionary<string, HealthBand>(StringComparer.Ordinal)
        {
            { "IF_MA", new HealthBand(50.0, 1000.0, "Ir_mA, Vf", "RDPMS: If mA / ITC FEED END(mA)") },
            { "IR_MA", new HealthBand(50.0, 500.0, "TPR_V, Vr", "RDPMS: Ir mA / ITC RELAY END(mA)") },
            { "VR", new HealthBand(0.5, 6.0, "Ir_mA", "RDPMS: Vr / VTC RELAY END(V)") },
            { "CHOKE_V", new HealthBand(0.2, 3.0, "Vf, If_mA", "RDPMS: Choke V / VTC CH FEED END(V)") },
            { "CHARGER_MA", new HealthBand(70.0, 3000.0, "Charger_OP_V", "RDPMS: Charger mA / ITC TFC O/P(mA)") },
            { "TPR_V", new HealthBand(5.0, 40.0, "TPR_Loc_V", "RDPMS: TPR V / VTC 24 DC TPR I/P(V)") },
            { "VF", new HealthBand(0.5, 6.0, "Vr", "RDPMS: Vf / VTC FEED END(V)") },
            { "CHARGER_V", new HealthBand(10.0, 125.0, "Charger_mA", "RDPMS: Charger V / VTC TFC I/P(V)") },
            { "CHARGER_OP_V", new HealthBand(1.0, 10.0, "Charger_mA, Charger_V", "RDPMS: Charger OP V / VTC TFC O/P(V)") },
            { "TPR_LOC_V", new HealthBand(5.0, 40.0, "TPR_V", "RDPMS: TPR V (Loc) / VTC 24 DC LOC(V)") },
            { "TR_V", new HealthBand(0.5, 5.0, "Ir_mA", "RDPMS: TR V (Relay) / VTC TR") },
            { "RG_V", new HealthBand(40.0, 150.0, "RG_MA", "RDPMS: RG V / VSIG RG") },
            { "RG_MA", new HealthBand(40.0, 180.0, "RG_V", "RDPMS: RG mA / ISIG RG") },
            { "DG_V", new HealthBand(40.0, 150.0, "DPR", "RDPMS: DG V / VSIG DG") },
            { "DG_MA", new HealthBand(40.0, 180.0, "DG_V", "RDPMS: DG mA / ISIG DG") },
            { "HG_V", new HealthBand(40.0, 150.0, "HPR", "RDPMS: HG V / VSIG HG") },
            { "HG_MA", new HealthBand(40.0, 180.0, "HG_V", "RDPMS: HG mA / ISIG HG") },
            { "HHG_V", new HealthBand(40.0, 150.0, "HHPR", "RDPMS: HHG V / VSIG HHG") },
            { "HHG_MA", new HealthBand(40.0, 180.0, "HHG_V", "RDPMS: HHG mA / ISIG HHG") },
            { "SHON_V", new HealthBand(70.0, 150.0, "ShOn_MA", "RDPMS: On Aspect V / VSHSIG ON") },
            { "SHON_MA", new HealthBand(20.0, 60.0, "ShOn_V", "RDPMS: On Aspect mA / ISHSIG ON") },
            { "SHOFF_V", new HealthBand(70.0, 150.0, "ShOff_MA", "RDPMS: Off Aspect V / VSHSIG OFF") },
            { "SHOFF_MA", new HealthBand(20.0, 60.0, "ShOff_V", "RDPMS: Off Aspect mA / ISHSIG OFF") },
            { "BUG_MA", new HealthBand(70.0, 180.0, "BUG_V", "RDPMS: BUG mA / IROSIG (BUG)") },
            { "HHPR", new HealthBand(15.0, 40.0, "HHG_MA", "RDPMS: HHPR / VSIG HHPR") },
            { "DPR", new HealthBand(15.0, 40.0, "DG_MA", "RDPMS: DPR / VSIG DPR") },
            { "HPR", new HealthBand(15.0, 40.0, "HG_MA", "RDPMS: HPR / VSIG HPR") },
            { "BUPR", new HealthBand(15.0, 40.0, "BUG_MA", "RDPMS: BUPR / VROSIG HPR (BUPR)") },
            { "AUG_MA", new HealthBand(40.0, 180.0, "AUG_V", "RDPMS: AUG mA / IROSIG (AUG)") },
            { "DUG_MA", new HealthBand(70.0, 180.0, "DUG_V", "RDPMS: DUG mA / IROSIG (DUG)") },
            { "EUG_MA", new HealthBand(70.0, 180.0, "EUG_V", "RDPMS: EUG mA / IROSIG (EUG)") },
            { "AUG_V", new HealthBand(40.0, 150.0, "AUPR", "RDPMS: AUG V / VROSIG (AUG)") },
            { "BUG_V", new HealthBand(40.0, 150.0, "BUPR", "RDPMS: BUG V / VROSIG (BUG)") },
            { "AUPR", new HealthBand(15.0, 40.0, "AUG_MA", "RDPMS: AUPR / VROSIG HPR (AUPR)") },
            { "DUG_V", new HealthBand(70.0, 150.0, "DUG_MA", "RDPMS: DUG V / VROSIG (DUG)") },
            { "DUPR", new HealthBand(15.0, 40.0, "DUG_MA", "RDPMS: DUPR / VROSIG HPR (DUPR)") },
            { "EUPR", new HealthBand(15.0, 40.0, "EUG_MA", "RDPMS: EUPR / VROSIG HPR (EUPR)") },
            { "CO_HG_MA", new HealthBand(70.0, 180.0, "Co_Hg_V", "RDPMS: Co_Hg mA / ICOSIG") },
            { "CO_HG_V", new HealthBand(70.0, 150.0, "Co_Hg_MA", "RDPMS: Co_Hg V / VCOSIG") },
            { "CO_HPR", new HealthBand(15.0, 40.0, "Co_Hg_MA", "RDPMS: Co_HPR / VCOSIG HPR") },
            { "EUG_V", new HealthBand(70.0, 150.0, "EUG_MA", "RDPMS: EUG V / VROSIG (EUG)") },
            { "SH_HPR", new HealthBand(15.0, 40.0, "ShOff_MA", "RDPMS: Sh-HPR / VSHSIG HPR") },
            { "PILOTROOT_MA", new HealthBand(70.0, 180.0, "PILOTRoot_V", "RDPMS: PILOTRoot mA") },
            { "PILOTROOT_V", new HealthBand(70.0, 150.0, "PILOTRoot_MA", "RDPMS: PILOTRoot V") },
            { "A_NWKR_V", new HealthBand(12.0, 35.0, "A_NWKR_LOC_V", "RDPMS: A End - NWKR / A VPT NWKR") },
            { "A_RWKR_V", new HealthBand(12.0, 35.0, "A_RWKR_LOC_V", "RDPMS: A End - RWKR / A VPT RWKR") },
            { "B_NWKR_V", new HealthBand(12.0, 35.0, "B_NWKR_LOC_V", "RDPMS: B End - NWKR / B VPT NWKR") },
            { "B_RWKR_V", new HealthBand(12.0, 35.0, "B_RWKR_LOC_V", "RDPMS: B End - RWKR / B VPT RWKR") },
            { "A_NWKR_LOC_V", new HealthBand(12.0, 40.0, "A_NWKR_V", "RDPMS: A End - NWKR (Loc) / A VPT 24 DC LOC N") },
            { "A_RWKR_LOC_V", new HealthBand(12.0, 35.0, "A_RWKR_V", "RDPMS: A End - RWKR (Loc) / A VPT 24 DC LOC R") },
            { "B_NWKR_LOC_V", new HealthBand(12.0, 35.0, "B_NWKR_V", "RDPMS: B End - NWKR (Loc) / B VPT 24 DC LOC N") },
            { "B_RWKR_LOC_V", new HealthBand(12.0, 35.0, "B_RWKR_V", "RDPMS: B End - RWKR (Loc) / B VPT 24 DC LOC R") },
            { "A_NW_C", new HealthBand(0.8, 6.0, "A_NW_V", "EdgeX: AC Normal Avg (EdgeX op)") },
            { "A_NW_T", new HealthBand(1700.0, 20000.0, "A_NW_C", "EdgeX: AC Normal OperationTime (EdgeX op)") },
            { "A_NW_V", new HealthBand(80.0, 135.0, "A_NW_C", "EdgeX: AV Normal Avg (EdgeX op)") },
            { "B_NW_C", new HealthBand(0.8, 6.0, "B_NW_V", "EdgeX: BC Normal Avg (EdgeX op)") },
            { "B_NW_T", new HealthBand(1700.0, 20000.0, "B_NW_C", "EdgeX: BC Normal OperationTime (EdgeX op)") },
            { "B_NW_V", new HealthBand(80.0, 135.0, "B_NW_C", "EdgeX: BV Normal Avg (EdgeX op)") },
            { "A_RW_C", new HealthBand(0.8, 6.0, "A_RW_V", "EdgeX: AC Reverse Avg (EdgeX op)") },
            { "A_RW_T", new HealthBand(1700.0, 20000.0, "A_RW_C", "EdgeX: AC Reverse OperationTime (EdgeX op)") },
            { "A_RW_V", new HealthBand(80.0, 135.0, "A_RW_C", "EdgeX: AV Reverse Avg (EdgeX op)") },
            { "B_RW_C", new HealthBand(0.8, 6.0, "B_RW_V", "EdgeX: BC Reverse Avg (EdgeX op)") },
            { "B_RW_T", new HealthBand(1700.0, 20000.0, "B_RW_C", "EdgeX: BC Reverse OperationTime (EdgeX op)") },
            { "B_RW_V", new HealthBand(80.0, 135.0, "B_RW_C", "EdgeX: BV Reverse Avg (EdgeX op)") },
        };

        // STAGE 3: cause_code (upper) -> list of alerting attribute Titles it maps to.
        // 151 codes.
        public static readonly Dictionary<string, string[]> CauseToAttributes =
            new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
        {
            { "TC TFC I/P VOLT LOW", new string[] { "VTC TFC I/P", "VIPS TR-1 110 AC" } },   // Track Circuit/Predictive
            { "TC BT CHG CURR HIGH", new string[] { "ITC BATT CHARG" } },   // Track Circuit/Predictive
            { "TC RAIL RES HIGH", new string[] { "RRAIL" } },   // Track Circuit/Predictive
            { "TC TR OVER ENERIZATION", new string[] { "ITC RELAY END" } },   // Track Circuit/Predictive
            { "TC TR CONTACT RES HIGH", new string[] { "VIPS DC R EXT", "VTC 24 DC LOC" } },   // Track Circuit/Predictive
            { "TC TPR I/P VOLT LOW", new string[] { "VTC 24 DC LOC", "VTC 24 DC TPR I/P" } },   // Track Circuit/Predictive
            { "TC TFC O/P VOLT LOW (Charging)", new string[] { "VTC TFC O/P", "ITC BATT CHARG", "VIPS TR-1 110 AC" } },   // Track Circuit/Predictive
            { "TC TFC O/P VOLT LOW (Discharging)", new string[] { "VTC TFC O/P", "ITC BATT CHARG", "VIPS TR-1 110 AC" } },   // Track Circuit/Predictive
            { "TC BT CHG CURR LOW", new string[] { "ITC BATT CHARG" } },   // Track Circuit/Predictive
            { "TC CH RES LOW", new string[] { "RTC CH FEED END" } },   // Track Circuit/Predictive
            { "TC CH RES HIGH", new string[] { "RTC CH FEED END" } },   // Track Circuit/Predictive
            { "TC VAR RES LOW", new string[] { "RTC VAR RES" } },   // Track Circuit/Predictive
            { "TC VAR RES HIGH", new string[] { "RTC VAR RES" } },   // Track Circuit/Predictive
            { "TC BALST/SLPR RES LOW", new string[] { "ITC RELAY END", "IBALST" } },   // Track Circuit/Predictive
            { "TC TR VOLT LOW", new string[] { "ITC RELAY END" } },   // Track Circuit/Predictive
            { "TC GJ SHORT", new string[] { "ITC RELAY END", "IBALST" } },   // Track Circuit/Predictive
            { "TC SHORT", new string[] { "ITC RELAY END", "IBALST" } },   // Track Circuit/Failure
            { "TC VAR RES OPEN", new string[] { "ITC RELAY END", "ITC FEED END", "RTC VAR RES" } },   // Track Circuit/Failure
            { "TC RAIL RES OPEN", new string[] { "ITC RELAY END", "ITC FEED END", "RRAIL" } },   // Track Circuit/Failure
            { "TC TR RELAY DEFECT", new string[] { "ITC RELAY END", "VIPS DC R EXT", "VTC 24 DC LOC" } },   // Track Circuit/Failure
            { "TC TR UP TPR DN", new string[] { "ITC RELAY END", "VTC 24 DC LOC", "VTC 24 DC TPR I/P" } },   // Track Circuit/Failure
            { "TC TPR RELAY DEFECT", new string[] { "ITC RELAY END", "VTC 24 DC TPR I/P" } },   // Track Circuit/Failure
            { "REASON UNKNOWN", new string[] {  } },   // Track Circuit/Failure
            { "TC CH RES OPEN", new string[] { "ITC RELAY END", "ITC FEED END", "RTC CH FEED END" } },   // Track Circuit/Failure
            { "TC TFC O/P VOLT FAIL", new string[] { "ITC RELAY END", "ITC FEED END", "VTC TFC O/P" } },   // Track Circuit/Failure
            { "TC CKT OPEN", new string[] { "ITC RELAY END", "ITC FEED END" } },   // Track Circuit/Failure
            { "SIG RG VOLT/CURR LOW", new string[] { "VSIG RG", "ISIG RG", "VIPS Sig-1 110 AC" } },   // Signal/Predictive
            { "SIG HG VOLT/CURR LOW", new string[] { "VSIG HG", "ISIG HG", "VIPS Sig-1 110 AC" } },   // Signal/Predictive
            { "SIG HHG VOLT/CURR LOW", new string[] { "VSIG HHG", "ISIG HHG", "VIPS Sig-1 110 AC" } },   // Signal/Predictive
            { "SIG DG VOLT/CURR LOW", new string[] { "VSIG DG", "ISIG DG", "VIPS Sig-1 110 AC" } },   // Signal/Predictive
            { "SIG RG CURR HIGH", new string[] { "ISIG RG" } },   // Signal/Predictive
            { "SIG HG CURR HIGH", new string[] { "ISIG HG" } },   // Signal/Predictive
            { "SIG HHG CURR HIGH", new string[] { "ISIG HHG" } },   // Signal/Predictive
            { "SIG DG CURR HIGH", new string[] { "ISIG DG" } },   // Signal/Predictive
            { "SIG HPR VOLT LOW", new string[] { "VSIG HPR", "VIPS DC R EXT" } },   // Signal/Predictive
            { "SIG HHPR VOLT LOW", new string[] { "VSIG HHPR", "VIPS DC R EXT" } },   // Signal/Predictive
            { "SIG DPR VOLT LOW", new string[] { "VSIG DPR", "VIPS DC R EXT" } },   // Signal/Predictive
            { "SHSIG ON ASPECT VOLT/CURR LOW", new string[] { "VSHSIG ON", "ISHSIG ON", "ISHSIG PILOT", "VIPS Sig-1 110 AC" } },   // Signal/Predictive
            { "SHSIG ON ASPECT CURR HIGH", new string[] { "ISHSIG ON", "ISHSIG PILOT" } },   // Signal/Predictive
            { "SHSIG OFF ASPECT VOLT/CURR LOW", new string[] { "VSHSIG OFF", "ISHSIG OFF", "ISHSIG PILOT", "VIPS Sig-1 110 AC" } },   // Signal/Predictive
            { "SHSIG OFF ASPECT CURR HIGH", new string[] { "ISHSIG OFF", "ISHSIG PILOT" } },   // Signal/Predictive
            { "SHSIG OFF ASPECT HPR VOLT LOW", new string[] { "VSHSIG HPR", "VIPS DC R EXT" } },   // Signal/Predictive
            { "COSIG ASPECT VOLT/CURR LOW", new string[] { "VCOSIG", "ICOSIG", "VIPS Sig-1 110 AC" } },   // Signal/Predictive
            { "COSIG ASPECT CURR HIGH", new string[] { "ICOSIG" } },   // Signal/Predictive
            { "COSIG HPR VOLT LOW", new string[] { "VCOSIG HPR", "VIPS DC R EXT" } },   // Signal/Predictive
            { "ROSIG ASPECT VOLT/CURR LOW", new string[] { "VROSIG", "IROSIG", "VIPS Sig-1 110 AC" } },   // Signal/Predictive
            { "ROSIG ASPECT CURR HIGH", new string[] { "IROSIG" } },   // Signal/Predictive
            { "ROSIG HPR VOLT LOW", new string[] { "VROSIG HPR", "VIPS DC R EXT" } },   // Signal/Predictive
            { "SIG RG VOLT/CURR FAIL", new string[] { "VSIG RG", "ISIG RG", "VIPS Sig-1 110 AC" } },   // Signal/Failure
            { "SIG RG RECR RELAY DEFECT", new string[] { "VSIG RG", "ISIG RG" } },   // Signal/Failure
            { "SIG RG UNKOWN", new string[] {  } },   // Signal/Failure
            { "SIG HG VOLT/CURR FAIL", new string[] { "VSIG HPR", "VSIG HG", "ISIG HG", "VIPS Sig-1 110 AC" } },   // Signal/Failure
            { "SIG HG HPR VOLT FAIL", new string[] { "VSIG HPR", "VIPS DC R EXT" } },   // Signal/Failure
            { "SIG HG HECR RELAY DEFECT", new string[] { "VSIG HPR", "VSIG HG", "ISIG HG" } },   // Signal/Failure
            { "SIG HG UNKOWN", new string[] {  } },   // Signal/Failure
            { "SIG HHG VOLT/CURR FAIL", new string[] { "VSIG HPR", "VSIG HHPR", "VSIG HG", "VSIG HHG", "ISIG HG", "ISIG HHG", "VIPS Sig-1 110 AC" } },   // Signal/Failure
            { "SIG HHG HHPR VOLT FAIL", new string[] { "VSIG HPR", "VSIG HHPR", "VIPS DC R EXT" } },   // Signal/Failure
            { "SIG HHG HHECR RELAY DEFECT", new string[] { "VSIG HPR", "VSIG HHPR", "VSIG HG", "VSIG HHG", "ISIG HG", "ISIG HHG" } },   // Signal/Failure
            { "SIG HHG UNKOWN", new string[] {  } },   // Signal/Failure
            { "SIG DG VOLT/CURR FAIL", new string[] { "VSIG DPR", "VSIG DG", "ISIG DG", "VIPS Sig-1 110 AC" } },   // Signal/Failure
            { "SIG DG DPR VOLT FAIL", new string[] { "VSIG DPR", "VIPS DC R EXT" } },   // Signal/Failure
            { "SIG DG DECR RELAY DEFECT", new string[] { "VSIG DPR", "VSIG DG", "ISIG DG" } },   // Signal/Failure
            { "SIG DG UNKOWN", new string[] {  } },   // Signal/Failure
            { "SIG BLANK", new string[] {  } },   // Signal/Failure
            { "SHSIG ON ASPECT VOLT/CURR FAIL", new string[] { "VSHSIG ON", "ISHSIG ON", "ISHSIG PILOT", "VIPS Sig-1 110 AC" } },   // Signal/Failure
            { "SHSIG ON ASPECT ECR RELAY DEFECT", new string[] { "VSHSIG ON", "ISHSIG ON", "ISHSIG PILOT" } },   // Signal/Failure
            { "SHSIG ON ASPECT REASON UNKNOWN", new string[] {  } },   // Signal/Failure
            { "SHSIG OFF ASPECT VOLT/CURR FAIL", new string[] { "VSHSIG HPR", "VSHSIG OFF", "ISHSIG OFF", "ISHSIG PILOT", "VIPS Sig-1 110 AC" } },   // Signal/Failure
            { "SHSIG OFF ASPECT HPR VOLT FAIL", new string[] { "VSHSIG HPR", "VIPS DC R EXT" } },   // Signal/Failure
            { "SHSIG OFF ASPECT ECR RELAY DEFECT", new string[] { "VSHSIG HPR", "VSHSIG OFF", "ISHSIG OFF", "ISHSIG PILOT" } },   // Signal/Failure
            { "SHSIG OFF ASPECT REASON UNKOWN", new string[] {  } },   // Signal/Failure
            { "COSIG ASPECT VOLT/CURR FAIL", new string[] { "VCOSIG HPR", "VCOSIG", "ICOSIG", "VIPS Sig-1 110 AC" } },   // Signal/Failure
            { "COSIG HPR VOLT FAIL", new string[] { "VCOSIG HPR", "VIPS DC R EXT" } },   // Signal/Failure
            { "COSIG HECR RELAY DEFECT", new string[] { "VCOSIG HPR", "VCOSIG", "ICOSIG" } },   // Signal/Failure
            { "COSIG REASON UNKOWN", new string[] {  } },   // Signal/Failure
            { "ROSIG ASPECT VOLT/CURR FAIL", new string[] { "VROSIG HPR", "VROSIG", "IROSIG", "VIPS Sig-1 110 AC" } },   // Signal/Failure
            { "ROSIG HPR VOLT FAIL", new string[] { "VROSIG HPR", "VIPS DC R EXT" } },   // Signal/Failure
            { "ROSIG UECR RELAY DEFECT", new string[] { "VROSIG HPR", "VROSIG", "IROSIG" } },   // Signal/Failure
            { "ROSIG REASON UNKOWN", new string[] {  } },   // Signal/Failure
            { "PT N TIME HIGH", new string[] { "TPT N" } },   // Point Machine/Predictive
            { "PT R TIME HIGH", new string[] { "TPT R" } },   // Point Machine/Predictive
            { "PT N VOLT/CURR LOW", new string[] { "VPT 110 DC LOC N", "IPT N", "VIPS 110 DC", "IIPS BATT CHAR 110 DC" } },   // Point Machine/Predictive
            { "PT R VOLT/CURR LOW", new string[] { "VPT 110 DC LOC R", "IPT R", "VIPS 110 DC", "IIPS BATT CHAR 110 DC" } },   // Point Machine/Predictive
            { "PT N IND VOLT LOW AT LOC", new string[] { "VPT 24 DC LOC N", "VIPS DC R EXT" } },   // Point Machine/Predictive
            { "PT R IND VOLT LOW AT LOC", new string[] { "VPT 24 DC LOC R", "VIPS DC R EXT" } },   // Point Machine/Predictive
            { "PT VOLT LOW AT NWKR", new string[] { "VPT 24 DC LOC N", "VPT NWKR" } },   // Point Machine/Predictive
            { "PT VOLT LOW AT RWKR", new string[] { "VPT 24 DC LOC R", "VPT RWKR" } },   // Point Machine/Predictive
            { "PT NWKR RELAY DEFECT", new string[] { "VPT NWKR" } },   // Point Machine/Failure
            { "PT N VOLT/CURR FAIL", new string[] { "VPT 110 DC LOC N", "IPT N", "VIPS 110 DC" } },   // Point Machine/Failure
            { "PT N OBS", new string[] { "VPT 110 DC LOC N", "IPT N", "TPT N" } },   // Point Machine/Failure
            { "PT RWKR RELAY DEFECT", new string[] { "VPT RWKR" } },   // Point Machine/Failure
            { "PT R VOLT/CURR FAIL", new string[] { "VPT 110 DC LOC R", "IPT R", "VIPS 110 DC" } },   // Point Machine/Failure
            { "PT R OBS", new string[] { "VPT 110 DC LOC R", "IPT R", "TPT R" } },   // Point Machine/Failure
            { "PT N IND VOLT FAIL AT LOC", new string[] { "VPT 24 DC LOC N", "VIPS DC R EXT" } },   // Point Machine/Failure
            { "PT R IND VOLT FAIL AT LOC", new string[] { "VPT 24 DC LOC R", "VIPS DC R EXT" } },   // Point Machine/Failure
            { "PT VOLT FAIL AT NWKR", new string[] { "VPT 24 DC LOC N", "VPT NWKR" } },   // Point Machine/Failure
            { "PT VOLT FAIL AT RWKR", new string[] { "VPT 24 DC LOC R", "VPT RWKR" } },   // Point Machine/Failure
            { "PT N FAIL UNKNOWN", new string[] {  } },   // Point Machine/Failure
            { "PT R FAIL UNKNOWN", new string[] {  } },   // Point Machine/Failure
            { "PT VOLT FAIL AT NWKR OP", new string[] { "VPT 110 DC LOC N", "IPT N", "VPT 24 DC LOC N", "VPT NWKR" } },   // Point Machine/Failure
            { "PT VOLT FAIL AT RWKR OP", new string[] { "VPT 110 DC LOC R", "IPT R", "VPT 24 DC LOC R", "VPT RWKR" } },   // Point Machine/Failure
            { "PT NWKR RELAY DEFECT OP", new string[] { "VPT 110 DC LOC N", "IPT N", "VPT NWKR" } },   // Point Machine/Failure
            { "PT RWKR RELAY DEFECT OP", new string[] { "VPT 110 DC LOC R", "IPT R", "VPT RWKR" } },   // Point Machine/Failure
            { "PT N FAIL UNKNOWN OP", new string[] {  } },   // Point Machine/Failure
            { "PT R FAIL UNKNOWN OP", new string[] {  } },   // Point Machine/Failure
            { "IPS 110V DC LOW", new string[] { "VIPS 110 DC" } },   // IPS/Predictive
            { "IPS 110V AC LOW", new string[] { "VIPS Sig-1 110 AC" } },   // IPS/Predictive
            { "IPS I/P VOLT LOW", new string[] { "VIPS I/P" } },   // IPS/Predictive
            { "IPS 110 DC BATT VOLT LOW (Charging)", new string[] { "VIPS 110 DC", "IIPS BATT CHAR 110 DC" } },   // IPS/Predictive
            { "IPS 110 DC BATT VOLT LOW (Discharging)", new string[] { "VIPS 110 DC", "IIPS BATT CHAR 110 DC" } },   // IPS/Predictive
            { "IPS 110 AC Sig-1 VOLT LOW", new string[] { "VIPS Sig-1 110 AC" } },   // IPS/Predictive
            { "IPS 110 AC TR-1 VOLT LOW", new string[] { "VIPS TR-1 110 AC" } },   // IPS/Predictive
            { "IPS SMR-1 VOLT LOW", new string[] { "VIPS SMR-1 110 DC" } },   // IPS/Predictive
            { "IPS DC-DC R INT VOLT LOW", new string[] { "VIPS DC R INT" } },   // IPS/Predictive
            { "IPS DC-DC R EXT VOLT LOW", new string[] { "VIPS DC R EXT" } },   // IPS/Predictive
            { "IPS DC-DC AXLE C VOLT LOW", new string[] { "VIPS DC AXLE C" } },   // IPS/Predictive
            { "IPS DC-DC PAN IND VOLT LOW", new string[] { "VIPS DC PAN IND" } },   // IPS/Predictive
            { "IPS DC-DC BLOCK LOCAL VOLT LOW", new string[] { "VIPS DC BLOCK LOCAL" } },   // IPS/Predictive
            { "IPS DC-DC HKT MAG VOLT LOW", new string[] { "VIPS DC HKT MAG" } },   // IPS/Predictive
            { "IPS DC-DC BLOCK LINE UP VOLT LOW", new string[] { "VIPS DC BLOCK LINE UP" } },   // IPS/Predictive
            { "IPS DC-DC BLOCK LINE DN VOLT LOW", new string[] { "VIPS DC BLOCK LINE DN" } },   // IPS/Predictive
            { "IPS DC-DC BLOCK TEL UP VOLT LOW", new string[] { "VIPS DC BLOCK TEL UP" } },   // IPS/Predictive
            { "IPS DC-DC BLOCK TEL DN VOLT LOW", new string[] { "VIPS DC BLOCK TEL DN" } },   // IPS/Predictive
            { "IPS DC-DC DATALOG VOLT LOW", new string[] { "VIPS DC DATALOG" } },   // IPS/Predictive
            { "IPS DC-DC EI VOLT LOW", new string[] { "VIPS DC EI" } },   // IPS/Predictive
            { "IPS BATT CHAR CURR LOW", new string[] { "IIPS BATT CHAR 110 DC" } },   // IPS/Predictive
            { "IPS 110V DC FAIL", new string[] { "VIPS 110 DC" } },   // IPS/Failure
            { "IPS 110V AC FAIL", new string[] { "VIPS Sig-1 110 AC" } },   // IPS/Failure
            { "IPS I/P VOLT FAIL", new string[] { "VIPS I/P" } },   // IPS/Failure
            { "IPS 110 DC VOLT FAIL", new string[] { "VIPS 110 DC" } },   // IPS/Failure
            { "IPS 110 AC Sig-1 VOLT FAIL", new string[] { "VIPS Sig-1 110 AC" } },   // IPS/Failure
            { "IPS 110 AC TR-1 VOLT FAIL", new string[] { "VIPS TR-1 110 AC" } },   // IPS/Failure
            { "IPS SMR-1 VOLT FAIL", new string[] { "VIPS SMR-1 110 DC" } },   // IPS/Failure
            { "IPS DC-DC R INT VOLT FAIL", new string[] { "VIPS DC R INT" } },   // IPS/Failure
            { "IPS DC-DC R EXT VOLT FAIL", new string[] { "VIPS DC R EXT" } },   // IPS/Failure
            { "IPS DC-DC AXLE C VOLT FAIL", new string[] { "VIPS DC AXLE C" } },   // IPS/Failure
            { "IPS DC-DC PAN IND VOLT FAIL", new string[] { "VIPS DC PAN IND" } },   // IPS/Failure
            { "IPS DC-DC BLOCK LOCAL VOLT FAIL", new string[] { "VIPS DC BLOCK LOCAL" } },   // IPS/Failure
            { "IPS DC-DC HKT MAG VOLT FAIL", new string[] { "VIPS DC HKT MAG" } },   // IPS/Failure
            { "IPS DC-DC BLOCK LINE UP VOLT FAIL", new string[] { "VIPS DC BLOCK LINE UP" } },   // IPS/Failure
            { "IPS DC-DC BLOCK LINE DN VOLT FAIL", new string[] { "VIPS DC BLOCK LINE DN" } },   // IPS/Failure
            { "IPS DC-DC BLOCK TEL UP VOLT FAIL", new string[] { "VIPS DC BLOCK TEL UP" } },   // IPS/Failure
            { "IPS DC-DC BLOCK TEL DN VOLT FAIL", new string[] { "VIPS DC BLOCK TEL DN" } },   // IPS/Failure
            { "IPS DC-DC DATALOG VOLT FAIL", new string[] { "VIPS DC DATALOG" } },   // IPS/Failure
            { "IPS DC-DC EI VOLT FAIL", new string[] { "VIPS DC EI" } },   // IPS/Failure
            { "IPS BATT CHAR CURR FAIL", new string[] { "IIPS BATT CHAR 110 DC" } },   // IPS/Failure
            { "IPS DC-DC BATT CHAR CURR FAIL", new string[] { "IIPS BATT CHAR 110 DC" } },   // IPS/Failure
        };

        // STAGE 4: point-machine EdgeX operation attid grid. Key = ASSETATTR|DIRECTION|DATATYPE (upper).
        // 48 entries. AC=A-Current AV=A-Voltage BC=B-Current BV=B-Voltage.
        public static readonly Dictionary<string, string> PmOpAttid =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "AC|Normal|Array", "1001" },
            { "AC|Normal|Avg", "1002" },
            { "AC|Normal|Min", "1003" },
            { "AC|Normal|Max", "1004" },
            { "AC|Normal|OperationTime", "1005" },
            { "AC|Normal|Count", "1006" },
            { "AV|Normal|Array", "2001" },
            { "AV|Normal|Avg", "2002" },
            { "AV|Normal|Min", "2003" },
            { "AV|Normal|Max", "2004" },
            { "AV|Normal|OperationTime", "2005" },
            { "AV|Normal|Count", "2006" },
            { "BC|Normal|Array", "3001" },
            { "BC|Normal|Avg", "3002" },
            { "BC|Normal|Min", "3003" },
            { "BC|Normal|Max", "3004" },
            { "BC|Normal|OperationTime", "3005" },
            { "BC|Normal|Count", "3006" },
            { "BV|Normal|Array", "4001" },
            { "BV|Normal|Avg", "4002" },
            { "BV|Normal|Min", "4003" },
            { "BV|Normal|Max", "4004" },
            { "BV|Normal|OperationTime", "4005" },
            { "BV|Normal|Count", "4006" },
            { "AC|Reverse|Array", "6001" },
            { "AC|Reverse|Avg", "6002" },
            { "AC|Reverse|Min", "6003" },
            { "AC|Reverse|Max", "6004" },
            { "AC|Reverse|OperationTime", "6005" },
            { "AC|Reverse|Count", "6006" },
            { "AV|Reverse|Array", "7001" },
            { "AV|Reverse|Avg", "7002" },
            { "AV|Reverse|Min", "7003" },
            { "AV|Reverse|Max", "7004" },
            { "AV|Reverse|OperationTime", "7005" },
            { "AV|Reverse|Count", "7006" },
            { "BC|Reverse|Array", "8001" },
            { "BC|Reverse|Avg", "8002" },
            { "BC|Reverse|Min", "8003" },
            { "BC|Reverse|Max", "8004" },
            { "BC|Reverse|OperationTime", "8005" },
            { "BC|Reverse|Count", "8006" },
            { "BV|Reverse|Array", "9001" },
            { "BV|Reverse|Avg", "9002" },
            { "BV|Reverse|Min", "9003" },
            { "BV|Reverse|Max", "9004" },
            { "BV|Reverse|OperationTime", "9005" },
            { "BV|Reverse|Count", "9006" },
        };


    }
}
