using Domain;
using E7MRIWeb.Areas.FRS25.Controllers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace E7.AiCore
{
    // ---- original file header of AiChatController.AiAudit.cs (kept verbatim) ----
    // <auto-generated-note>
    // AiChatController.AiAudit.cs -- v1.0.160.74
    // Partial of AiChatController holding the AI audit DB client (EdgeX DataAPI 1.5.57.x,
    // AI_ALERT_* tables). Split out at the owner's request: AiChatController.cs had reached 15,261
    // lines and this subsystem is self-contained -- config, capability probe, circuit breaker, POST
    // helper and the two write points, with no reach into the verdict logic.
    //
    // FAIL-OPEN CONTRACT (do not weaken):
    //   * every method returns null/void/0 on ANY failure -- no exception may reach a verdict;
    //   * the version probe keeps it silent on a DataAPI older than AiAuditDbMinVersion;
    //   * the breaker stops an absent or sick API costing a round trip on every alert;
    //   * its own HttpClient, so it can never inherit the 600s DeepSeek timeout;
    //   * Start failing yields id 0, which simply skips child writes -- a partial state, not a cascade.
    // </auto-generated-note>
    // ---- end of original header ----
    // AnalysisEngine -- AiAudit.
    // Moved verbatim from AiChatController.AiAudit.cs in 1.0.165.0 (Shared AI Core 2e);
    // only access modifiers changed (private -> internal). The web app sees internals via InternalsVisibleTo.
    public sealed partial class AnalysisEngine
    {
        // v1.0.160.73: AI audit DB (EdgeX DataAPI). Ships OFF -- the routes do not exist on the
        // DataAPI running today (1.5.55.9 < 1.5.57.0).
        internal static readonly bool _auditDbEnabled = ReadBool("AiAuditDbEnabled", false);

        internal static readonly string _auditDbUrl = ReadStr("AiAuditDbBaseUrl", "http://172.31.25.103:8083").TrimEnd('/');

        internal static readonly int _auditDbTimeoutMs = ClampCfg(ReadInt("AiAuditDbTimeoutMs", 1500), 200, 15000);

        internal static readonly int _auditDbMaxFail = ClampCfg(ReadInt("AiAuditDbMaxFail", 3), 1, 20);

        internal static readonly int _auditDbRetryMin = ClampCfg(ReadInt("AiAuditDbRetryMin", 10), 1, 240);

        internal static readonly string _auditDbMinVer = ReadStr("AiAuditDbMinVersion", "1.5.57.0");

        internal static int _auditFails;

        internal static DateTime _auditDormantUntil = DateTime.MinValue;

        internal static int _auditCapable = -1;   // -1 unknown, 0 absent, 1 present

        internal static readonly object _auditLock = new object();

        internal static readonly HttpClient _auditHttp = BuildAuditHttp();

        internal static HttpClient BuildAuditHttp()
        {
            // Its OWN client: it must never inherit the 600s DeepSeek timeout.
            HttpClient h = new HttpClient();
            try { h.Timeout = TimeSpan.FromMilliseconds(ClampCfg(ReadInt("AiAuditDbTimeoutMs", 1500), 200, 15000)); }
            catch { }
            return h;
        }


        // v1.0.160.78: one AI_ALERT_Request row per run, then ALL its MCP calls in ONE post.
        // Ordering is forced by the contract: McpCall requires a RequestId, which only exists after
        // Request/Start returns one -- so these are a single unit, and if Start fails the calls are
        // dropped rather than written against a null parent.
        internal void AuditRequestAndCalls(JObject audit, JObject ctx)
        {
            try
            {
                if (Sess._auditAnalysisId <= 0) { return; }
                JObject who = audit != null ? audit["who"] as JObject : null;
                JObject which = audit != null ? audit["which"] as JObject : null;
                JObject cost = audit != null ? audit["cost"] as JObject : null;
                JObject when = audit != null ? audit["when"] as JObject : null;

                JObject rq = new JObject();
                rq["AnalysisId"] = Sess._auditAnalysisId;
                rq["SessionId"] = Sess._traceId;
                rq["TurnIndex"] = 0;
                if (who != null)
                {
                    if (who["user"] != null) { rq["UserName"] = who["user"]; }
                    if (who["role"] != null) { rq["UserRole"] = who["role"]; }
                    if (who["ip"] != null) { rq["UserIp"] = who["ip"]; }
                }
                rq["RequestedAtUtc"] = Sess._reqStartUtc.ToString("o");
                rq["SiteId"] = CtxLong(ctx, "siteId");
                rq["SiteName"] = GetCtx(ctx, "station");
                try { rq["ServerNode"] = Environment.MachineName; } catch { }
                rq["ApiEndpoint"] = "AnalyzeAlert";
                rq["ControllerVersion"] = ComponentVersion;
                rq["Engine"] = Sess._provider ?? "";
                rq["Provider"] = ProviderKind;
                if (which != null)
                {
                    if (which["model"] != null) { rq["ModelId"] = which["model"]; }
                    if (which["thinking"] != null) { rq["ThinkingEnabled"] = which["thinking"]; }
                    if (which["roleGated"] != null) { rq["GatedByRole"] = which["roleGated"]; }
                }
                if (rq["ModelId"] == null) { rq["ModelId"] = ReadStr("DeepSeekModel", ""); }
                rq["RequestType"] = "verdict";
                rq["AlertId"] = CtxLong(ctx, "alertId");
                rq["AlertType"] = GetCtx(ctx, "alertType");
                rq["CauseCode"] = GetCtx(ctx, "causeCode");
                rq["AssetId"] = CtxLong(ctx, "assetId");
                rq["AssetName"] = GetCtx(ctx, "assetName");
                if (!string.IsNullOrEmpty(Sess._lastPromptFull)) { rq["SystemPrompt"] = PgSafe(Sess._lastPromptFull, 0); }
                rq["RespondedAtUtc"] = DateTime.UtcNow.ToString("o");   // required by the server

                JObject r = AuditPost("/api/AIRequest/Start", rq);
                long reqId = 0;
                if (r != null && r["RequestId"] != null) { long.TryParse(r["RequestId"].ToString(), out reqId); }
                if (reqId <= 0) { McpDrain(Sess._traceId); return; }   // drop the calls, never orphan them

                JObject rc = new JObject();
                rc["RequestId"] = reqId;
                rc["AnalysisId"] = Sess._auditAnalysisId;
                rc["RespondedAtUtc"] = DateTime.UtcNow.ToString("o");
                if (when != null && when["totalMs"] != null) { rc["LatencyMs"] = when["totalMs"]; }
                if (cost != null)
                {
                    if (cost["tokIn"] != null) { rc["TokensIn"] = cost["tokIn"]; }
                    if (cost["tokOut"] != null) { rc["TokensOut"] = cost["tokOut"]; }
                    if (cost["costUsdEst"] != null) { rc["EstCostUsd"] = cost["costUsdEst"]; }
                    if (cost["toolCalls"] != null) { rc["McpToolCallCount"] = cost["toolCalls"]; }
                    if (cost["iterations"] != null) { rc["IterationCount"] = cost["iterations"]; }
                }
                if (Sess._lastVerdictSummary != null)
                {
                    if (Sess._lastVerdictSummary["verdict"] != null) { rc["Verdict"] = Sess._lastVerdictSummary["verdict"].ToString(); }
                    if (Sess._lastVerdictSummary["confidence"] != null) { rc["Confidence"] = Sess._lastVerdictSummary["confidence"].ToString(); }
                }
                if (Sess._computedVerdict != null && Sess._computedVerdict["class"] != null) { rc["ComputedVerdict"] = Sess._computedVerdict["class"].ToString(); }
                rc["ComputedWon"] = Sess._computedWonLast;
                if (!string.IsNullOrEmpty(Sess._lastResponseFull)) { rc["FullResponseJson"] = PgSafe(Sess._lastResponseFull, 0); }
                AuditPost("/api/AIRequest/Complete", rc);

                // ALL calls of the run in ONE post -- McpCall/Add loops a JSON array server-side.
                List<JObject> calls = McpDrain(Sess._traceId);
                if (calls == null || calls.Count == 0) { return; }
                JArray arr = new JArray();
                for (int i = 0; i < calls.Count; i++)
                {
                    JObject c = calls[i];
                    c["RequestId"] = reqId;
                    c["AnalysisId"] = Sess._auditAnalysisId;
                    c["CallIndex"] = i;
                    c["SiteId"] = CtxLong(ctx, "siteId");
                    c["AlertId"] = CtxLong(ctx, "alertId");
                    c["Engine"] = Sess._provider ?? "";
                    if (c["ToolArgsJson"] != null) { c["ToolArgsJson"] = PgSafe(c["ToolArgsJson"].ToString(), 0); }
                    if (c["ToolResultJson"] != null) { c["ToolResultJson"] = PgSafe(c["ToolResultJson"].ToString(), 0); }
                    arr.Add(c);
                }
                AuditPostArray("/api/AIMcpCall/Add", arr);
                AiLog("INFO", "AUDITDB", "request " + reqId + " + " + arr.Count + " mcp calls written");
            }
            catch { }
        }


        // v1.0.160.78: follow-up chat turn.
        // v1.0.160.94: takes ctx so AlertId can be sent. EdgeX 1.5.57.6 added AlertId to
        // AI_ALERT_ChatHistory precisely so a thread can be fetched per ALERT -- without it a
        // second engineer's turns sit under a different AnalysisId and stay invisible.
        internal void AuditChatTurn(int turnIndex, string role, string message, JObject ctx)
        {
            try
            {
                if (Sess._auditAnalysisId <= 0 || string.IsNullOrEmpty(message)) { return; }
                JObject b = new JObject();
                b["AnalysisId"] = Sess._auditAnalysisId;
                b["SessionId"] = Sess._traceId;
                b["AlertId"] = CtxLong(ctx, "alertId");   // v1.0.160.94
                // v1.0.160.85: captured before the first await; LoginUser is null by this point.
                string usr = Sess._luName ?? "";
                b["UserName"] = usr.Length > 0 ? usr : "ENERGY7";
                b["TurnIndex"] = turnIndex;
                b["MessageRole"] = role;
                b["MessageText"] = PgSafe(message, 20000);   // v1.0.160.94: the readable column
                b["MessageJson"] = PgSafe(message, 20000);
                System.Threading.Tasks.Task.Run(() => { try { AuditPost("/api/AIChat/Append", b); } catch { } });
            }
            catch { }
        }


        // v1.0.160.78: array-bodied POST (McpCall/Add loops a JSON array).
        internal static JObject AuditPostArray(string route, JArray body)
        {
            if (!AuditReady() || body == null) { return null; }
            try
            {
                var content = new StringContent(body.ToString(Formatting.None), Encoding.UTF8, "application/json");
                var t = _auditHttp.PostAsync(_auditDbUrl + route, content);
                if (!t.Wait(_auditDbTimeoutMs)) { throw new Exception("timeout"); }
                var resp = t.Result;
                if (!resp.IsSuccessStatusCode)
                {
                    string et = "";
                    try { var rt2 = resp.Content.ReadAsStringAsync(); rt2.Wait(_auditDbTimeoutMs); et = rt2.Result; } catch { }
                    AuditNoteFailure(route + " -> HTTP " + (int)resp.StatusCode
                        + (string.IsNullOrEmpty(et) ? "" : " :: " + Trunc(et.Replace("\r", " ").Replace("\n", " "), 400)));
                    return null;
                }
                lock (_auditLock) { _auditFails = 0; }
                return new JObject();
            }
            catch (Exception ex) { AuditNoteFailure(route + " -> " + ex.Message); return null; }
        }


        // v1.0.160.77: stable identity of the ALERT AS PRESENTED -- cause + asset + incidence +
        // the triggered measured values. Two analyses of the same unchanged alert produce the same
        // fingerprint; if the card changes (a new measured value, a different cause) it changes, which
        // is exactly what the verdict cache needs to know the stored answer no longer describes this
        // alert. BYTEA column, so the hex string is what the API expects.
        internal static string AlertFingerprintHex(JObject ctx)
        {
            try
            {
                if (ctx == null) { return null; }
                StringBuilder sb = new StringBuilder();
                sb.Append(GetCtx(ctx, "causeCode")).Append('|')
                  .Append(GetCtx(ctx, "assetName")).Append('|')
                  .Append(GetCtx(ctx, "time")).Append('|')
                  .Append(GetCtx(ctx, "siteId")).Append('|');
                JObject card = ctx["alertCard"] as JObject;
                JArray tc = card != null ? card["triggeredConditions"] as JArray : null;
                if (tc != null)
                {
                    for (int i = 0; i < tc.Count; i++)
                    {
                        JObject c = tc[i] as JObject;
                        if (c == null) { continue; }
                        if (c["paramLabel"] != null) { sb.Append(c["paramLabel"].ToString()).Append('='); }
                        if (c["measured"] != null) { sb.Append(c["measured"].ToString()); }
                        sb.Append(';');
                    }
                }
                using (var sha = System.Security.Cryptography.SHA256.Create())
                {
                    byte[] h = sha.ComputeHash(Encoding.UTF8.GetBytes(sb.ToString()));
                    StringBuilder hex = new StringBuilder(h.Length * 2);
                    for (int i = 0; i < h.Length; i++) { hex.Append(h[i].ToString("x2")); }
                    return hex.ToString();
                }
            }
            catch { return null; }
        }


        // v1.0.160.76: make a string safe for a PostgreSQL TEXT column.
        // Two hazards, both real for verdict text that carries Hinglish and symbols:
        //  (1) LONE SURROGATE -- Trunc/TraceTrunc use a raw Substring, so a cut can land BETWEEN the
        //      high and low half of a surrogate pair. PostgreSQL rejects the resulting invalid UTF-8
        //      outright (22021) and the WHOLE insert fails, not just that column.
        //  (2) NUL (0x00) -- a PG TEXT column cannot hold it at any position.
        // JSON nesting itself needs no encoding: Newtonsoft escapes the inner document when it
        // serialises the outer one, and the server unescapes it, so the column receives clean JSON.
        // Base64 would only make the column unreadable in psql for no gain.
        internal static string PgSafe(string v, int max)
        {
            if (string.IsNullOrEmpty(v)) { return v; }
            StringBuilder sb = new StringBuilder(v.Length);
            for (int i = 0; i < v.Length; i++)
            {
                char c = v[i];
                if (c == '\0') { continue; }                       // PG TEXT cannot store NUL
                // v1.0.160.88: C1 controls U+0080-U+009F. The server rejected our insert with
                // "invalid byte sequence for encoding UTF8: 0x97" -- 0x97 is the CP-1252 em-dash,
                // arriving because FRS alert text originates in a CP-1252 SQL Server column. These
                // code points carry no legitimate text meaning, so drop them outright.
                if (c >= '\u0080' && c <= '\u009F') { continue; }
                // Smart punctuation -> ASCII. Same house rule as the C# sources: keep what reaches
                // PostgreSQL plain, rather than relying on every layer to re-encode correctly.
                if (c == '\u2013' || c == '\u2014') { sb.Append('-'); continue; }      // en/em dash
                if (c == '\u2018' || c == '\u2019') { sb.Append('\''); continue; }     // curly single
                if (c == '\u201C' || c == '\u201D') { sb.Append('"'); continue; }      // curly double
                if (c == '\u2026') { sb.Append("..."); continue; }                      // ellipsis
                if (c == '\u00A0') { sb.Append(' '); continue; }                        // nbsp
                if (char.IsHighSurrogate(c))
                {
                    if (i + 1 < v.Length && char.IsLowSurrogate(v[i + 1]))
                    { sb.Append(c).Append(v[i + 1]); i++; }         // keep the PAIR together
                    continue;                                        // drop an unpaired high half
                }
                if (char.IsLowSurrogate(c)) { continue; }            // drop an orphaned low half
                sb.Append(c);
            }
            string outp = sb.ToString();
            if (max > 0 && outp.Length > max)
            {
                int cut = max;
                // never cut between the halves of a pair
                if (cut > 0 && char.IsHighSurrogate(outp[cut - 1])) { cut--; }
                outp = outp.Substring(0, cut);
            }
            return outp;
        }


        // v1.0.160.74: numeric context read for the Int columns. "" or unparsable -> 0.
        internal static long CtxLong(JObject o, string key)
        {
            long v;
            string raw = GetCtx(o, key);
            if (!string.IsNullOrEmpty(raw) && long.TryParse(raw.Trim(), out v)) { return v; }
            return 0;
        }


        // v1.0.160.73: open the analysis row. Returns 0 on ANY failure -- and 0 means every child
        // write is skipped, which is a correct partial state rather than a cascade of errors.
        internal long AuditStartAnalysis(JObject ctx)
        {
            try
            {
                if (!_auditDbEnabled) { return 0; }
                JObject b = new JObject();
                b["SessionId"] = Sess._traceId;                       // per-run id: joins to trace + JSONL
                // v1.0.160.74: AlertId and SiteId are Int columns server-side. GetCtx returns "" (not
                // null) when absent, so the required-field check PASSES and the failure would surface
                // as a 500 on type conversion -- and 500s do not carry the AlertId echo that 1.5.57.1
                // added, making them the hardest to trace. Send 0 rather than depend on server coercion.
                b["AlertId"] = CtxLong(ctx, "alertId");
                b["AlertType"] = GetCtx(ctx, "alertType");
                b["CauseCode"] = GetCtx(ctx, "causeCode");
                b["SiteId"] = CtxLong(ctx, "siteId");
                b["SiteName"] = GetCtx(ctx, "station");
                b["AlertInputJson"] = PgSafe(ctx != null ? ctx.ToString(Formatting.None) : "{}", 0);
                b["Engine"] = Sess._provider ?? "";
                b["Provider"] = ProviderKind;
                string mo = AnalysisModelOverride;
                b["ModelId"] = !string.IsNullOrEmpty(mo) ? mo
                    : (ProviderKind == "deepseek" ? ReadStr("DeepSeekModel", "")
                    : (ProviderKind == "openai" ? ReadStr("OpenAiModel", "") : ReadStr("AnthropicModel", "")));
                // v1.0.160.100: the live row 37 came back with AssetId, AssetName, AssetType,
                // UserName, UserRole and ServerNode ALL NULL. They were being sent on the REQUEST row
                // only -- so the Analysis table, which is the one the cache and every future query
                // read, could not say which asset or which operator an analysis belonged to.
                b["AssetId"] = CtxLong(ctx, "assetId");
                b["AssetName"] = GetCtx(ctx, "assetName");
                b["AssetType"] = GetCtx(ctx, "assetType");
                if (!string.IsNullOrEmpty(Sess._luName)) { b["UserName"] = Sess._luName; }
                b["UserRole"] = (Sess._luSiteKeep || SafeIsSiteKeeping()) ? "sitekeeping" : "operator";
                try { b["ServerNode"] = Environment.MachineName; } catch { }
                b["ControllerVersion"] = ComponentVersion;
                // v1.0.160.100: Flag_* live on the START whitelist. Set from what is ALREADY known
                // at open time -- the gated-derived setting and whether strict coverage is on. The
                // two that are only knowable at the END (train context found, computed verdict
                // produced) cannot be set here and are carried instead by TrainContextCount and
                // ComputedVerdict on Complete, which are whitelisted and do reach the row.
                b["Flag_GatedDerived"] = ReadBool("AnalyzeGatedDerived", false);
                b["Flag_StrictCoverage"] = ReadBool("AnalyzeStrictCoverage", true);
                // v1.0.160.189: fill Start columns we already hold (whitelist ignores unknown keys).
                // AlertTriggeredAtUtc: ctx["time"] is IST wall-clock -> store true UTC (-5:30). TIMESTAMPTZ.
                {
                    DateTime _atIst;
                    if (TryParseAlertTime(GetCtx(ctx, "time"), out _atIst))
                    { b["AlertTriggeredAtUtc"] = _atIst.AddHours(-5).AddMinutes(-30).ToString("yyyy-MM-ddTHH:mm:ssZ"); }
                }
                b["AnalysisStartedUtc"] = DateTime.UtcNow.ToString("o");     // TIMESTAMPTZ NOT NULL
                b["ThinkingEnabled"] = ThinkOn;                             // BOOLEAN
                { string _sev = GetCtx(ctx, "severity"); if (!string.IsNullOrEmpty(_sev)) { b["AlertSeverity"] = PgSafe(_sev, 16); } }   // VARCHAR(16)
                { string _pv = ReadStr("AnalyzePromptVersion", ""); if (!string.IsNullOrEmpty(_pv)) { b["PromptVersion"] = PgSafe(_pv, 32); } }
                JObject r = AuditPost("/api/AIAnalysis/Start", b);
                if (r == null) { return 0; }
                long id = 0;
                if (r["AnalysisId"] != null) { long.TryParse(r["AnalysisId"].ToString(), out id); }
                else if (r["data"] != null && r["data"]["AnalysisId"] != null) { long.TryParse(r["data"]["AnalysisId"].ToString(), out id); }
                if (id > 0) { AiLog("INFO", "AUDITDB", "analysis row " + id + " opened"); }
                return id;
            }
            catch { return 0; }
        }


        // v1.0.160.73: close the row from the SAME 7W object the JSONL uses, so file and DB cannot
        // drift. Fire-and-forget: nothing waits on it.
        internal void AuditCompleteAnalysis(JObject audit, bool failed, string failReason)
        {
            try
            {
                if (Sess._auditAnalysisId <= 0) { return; }
                JObject b = new JObject();
                b["AnalysisId"] = Sess._auditAnalysisId;
                if (failed)
                {
                    b["AnalysisStatus"] = "FAILED";
                    b["FailReason"] = PgSafe(failReason ?? "unknown", 400);
                    System.Threading.Tasks.Task.Run(() => { try { AuditPost("/api/AIAnalysis/Fail", b); } catch { } });
                    return;
                }

                // v1.0.160.75: map onto the columns the server actually whitelists. 160.73 sent
                // "AuditJson", which is NOT a column in DBSchema_AI.sql and NOT in the API whitelist --
                // CollectColumns silently drops unknown keys, so the whole 7W record was going nowhere.
                // Worse for what comes next: AnalysisOutputJson was never populated, so a verdict cache
                // would find a row with NO verdict to serve.
                // v1.0.160.83: the server accepts COMPLETED | CACHED | REANALYSIS here (FAILED goes to
                // /Fail, which is already correct). I sent "COMPLETE" -- one letter short -- and every
                // Complete returned 400, so rows were opened and never closed.
                b["AnalysisStatus"] = "COMPLETED";
                b["AnalysisCompletedUtc"] = DateTime.UtcNow.ToString("o");
                if (!string.IsNullOrEmpty(Sess._lastResponseFull)) { b["AnalysisOutputJson"] = PgSafe(Sess._lastResponseFull, 0); }
                // v1.0.160.143: SAY whether a payload went with it. The open is logged
                // ("analysis row N opened") and the close was silent, so a row completed WITH a
                // verdict and a row completed EMPTY produced the identical log -- and an empty one
                // is exactly what stops the cache serving. Absent must not look like negative.
                AiLog(string.IsNullOrEmpty(Sess._lastResponseFull) ? "WARN" : "INFO", "AUDITDB",
                    "analysis row " + Sess._auditAnalysisId + " completed "
                    + (string.IsNullOrEmpty(Sess._lastResponseFull)
                        ? "with NO verdict payload -- this row cannot be served from cache"
                        : "with verdict payload (" + Sess._lastResponseFull.Length + " chars)"));
                if (Sess._lastVerdictSummary != null)
                {
                    if (Sess._lastVerdictSummary["verdict"] != null) { b["FinalVerdict"] = Sess._lastVerdictSummary["verdict"].ToString(); }
                    if (Sess._lastVerdictSummary["confidence"] != null)
                    {
                        int cf; if (int.TryParse(Sess._lastVerdictSummary["confidence"].ToString(), out cf)) { b["FinalConfidence"] = cf.ToString(); }   // v1.0.160.189: column is VARCHAR(16) -- send string, not int
                    }
                    if (Sess._lastVerdictSummary["headline"] != null) { b["FinalReasoning"] = PgSafe(Sess._lastVerdictSummary["headline"].ToString(), 2000); }
                }
                if (audit != null)
                {
                    JObject cost = audit["cost"] as JObject;
                    JObject when = audit["when"] as JObject;
                    JObject wis = audit["wisdom"] as JObject;
                    JObject which = audit["which"] as JObject;
                    if (cost != null)
                    {
                        if (cost["tokIn"] != null) { b["TotalTokensIn"] = cost["tokIn"]; }
                        if (cost["tokOut"] != null) { b["TotalTokensOut"] = cost["tokOut"]; }
                        // v1.0.160.189: TotalTokens is a GENERATED STORED column (In+Out+Thinking) --
                        // do NOT send it (write fails). Send TotalTokensThinking (a real INT) instead;
                        // the DB computes the total.
                        if (cost["tokThinking"] != null) { b["TotalTokensThinking"] = cost["tokThinking"]; }
                        if (cost["toolCalls"] != null) { b["McpToolCallTotal"] = cost["toolCalls"]; }
                        if (cost["iterations"] != null) { b["AiTurnCount"] = cost["iterations"]; }
                        if (cost["costUsdEst"] != null) { b["TotalEstCostUsd"] = cost["costUsdEst"]; }
                    }
                    if (when != null)
                    {
                        if (when["totalMs"] != null) { b["TotalDurationMs"] = when["totalMs"]; }
                        if (when["modelMs"] != null) { b["ModelDurationMs"] = when["modelMs"]; }
                    }
                    if (which != null && which["thinking"] != null) { b["ThinkingEnabled"] = which["thinking"]; }
                    if (wis != null && wis["driverSet"] != null) { b["EvidenceSummary"] = PgSafe(wis.ToString(Formatting.None), 4000); }   // TEXT column, no width limit
                }
                // v1.0.160.77: the columns that make the row QUERYABLE rather than archival.
                if (Sess._computedVerdict != null)
                {
                    if (Sess._computedVerdict["class"] != null) { b["ComputedVerdict"] = Sess._computedVerdict["class"].ToString(); }
                    if (Sess._computedVerdict["durSec"] != null) { b["BreachDurationSec"] = Sess._computedVerdict["durSec"]; }
                    if (Sess._computedVerdict["needSec"] != null) { b["FrsSustainSec"] = Sess._computedVerdict["needSec"]; }
                }
                b["ComputedWon"] = Sess._computedWonLast;
                b["GatedDerivedApplied"] = Sess._gateDroppedLast > 0;
                b["GatedSamplesRemoved"] = Sess._gateDroppedLast;
                // v1.0.160.189: queryable flags (BOOLEAN columns) so a filter can find rows where a
                // computed verdict / train context actually engaged. Schema has them on this insert.
                b["Flag_ComputedVerdict"] = Sess._computedVerdict != null;
                b["Flag_TrainContext"] = Sess._trainContext != null;
                if (Sess._trainContext != null)
                {
                    JArray tm = Sess._trainContext["matches"] as JArray;
                    b["TrainContextCount"] = tm != null ? tm.Count : 0;
                    // v1.0.160.82: the column is VARCHAR(512) -- I capped at 4000 without checking
                    // the schema, which would overflow and fail the WHOLE Complete insert.
                    b["TrainContextSummary"] = PgSafe(Sess._trainContext.ToString(Formatting.None), 500);
                }
                if (Sess._lastVerdictSummary != null && Sess._lastVerdictSummary["headline"] != null)
                {
                    // FinalReasoning already holds the headline; recommendation is the action line.
                    JToken ra = Sess._lastVerdictSummary["recommended_action"];
                    if (ra != null) { b["FinalRecommendation"] = PgSafe(ra.ToString(), 2000); }
                }
                string fp = AlertFingerprintHex(Sess._prefetchCtx);
                if (!string.IsNullOrEmpty(fp))
                {
                    b["AlertFingerprint"] = fp;
                    b["AlertFingerprintVersion"] = 1;
                }
                // v1.0.160.189: EvidenceFingerprint (BYTEA) -- SHA-256 of the evidence summary, so
                // identical evidence sets are detectable/dedupable server-side (indexed column).
                try
                {
                    JObject _wf = audit != null ? audit["wisdom"] as JObject : null;
                    if (_wf != null && _wf["driverSet"] != null)
                    {
                        using (var _sha = System.Security.Cryptography.SHA256.Create())
                        {
                            byte[] _h = _sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(_wf.ToString(Formatting.None)));
                            b["EvidenceFingerprint"] = BitConverter.ToString(_h).Replace("-", "");
                        }
                    }
                }
                catch { }
                // v1.0.160.100: the Flag_* columns exist so a query can filter on which mechanisms
                // actually engaged. They were never sent, so every row read false and the whole set
                // was indistinguishable from "nothing engaged". Flag_TrainContext read false on a row
                // that HAD a train-context summary, which is worse than absent -- it is wrong.
                // v1.0.160.100: the Flag_* columns are whitelisted on the START insert, not on
                // Complete -- so they are set THERE (see AuditStartAnalysis). Sending them here
                // would be silently dropped, the exact 160.75 trap where a 200 stored nothing.
                // v1.0.160.154: degraded as a QUERYABLE column, not only inside the JSON
                // payload -- the future AssetId= analysis-history query must filter degraded rows
                // without pulling the heavy AnalysisOutputJson, and LogWatch can count them per
                // day. NOTE: silently dropped by the server's CollectColumns whitelist until
                // DataAPI adds the DegradedInputs column; the .153 in-JSON stamp stays the
                // authority either way.
                if (Sess._e7ApiInputFailed)
                {
                    b["DegradedInputs"] = true;
                }
                b["McpTotalLatencyMs"] = Sess._trToolMs;
                b["PrefetchDurationMs"] = Sess._trPrefetchCalls > 0 ? Sess._trDiscoveryMs : 0;
                b["McpToolsDistinct"] = Sess._trPrefetchCalls;
                System.Threading.Tasks.Task.Run(() => { try { AuditPost("/api/AIAnalysis/Complete", b); } catch { } });
            }
            catch { }
        }


        // v1.0.160.73: capability probe. The DataAPI root returns {message, version}; /api/AI* only
        // exists from 1.5.57.0. Probing the VERSION once beats discovering absence through a 404 on
        // every call -- today the running API is 1.5.55.9, so this returns false and nothing is ever
        // attempted.
        internal static bool AuditVersionAtLeast(string running, string min)
        {
            try
            {
                string[] a = (running ?? "").Split('.');
                string[] b = (min ?? "").Split('.');
                for (int i = 0; i < 4; i++)
                {
                    int av = 0, bv = 0;
                    if (i < a.Length) { int.TryParse(a[i].Trim(), out av); }
                    if (i < b.Length) { int.TryParse(b[i].Trim(), out bv); }
                    if (av != bv) { return av > bv; }
                }
                return true;
            }
            catch { return false; }
        }


        // Returns false whenever the audit DB must NOT be called: disabled, dormant, or the running
        // DataAPI predates the AI routes. Never throws.
        internal static bool AuditReady()
        {
            try
            {
                if (!_auditDbEnabled) { return false; }
                lock (_auditLock)
                {
                    if (DateTime.UtcNow < _auditDormantUntil) { return false; }
                    if (_auditCapable == 0) { return false; }
                    if (_auditCapable == 1) { return true; }
                }
                // one probe per process (or per dormancy expiry)
                string ver = "";
                try
                {
                    var t = _auditHttp.GetStringAsync(_auditDbUrl + "/");
                    if (!t.Wait(_auditDbTimeoutMs)) { throw new Exception("probe timeout"); }
                    JObject o = JObject.Parse(t.Result);
                    ver = o["version"] != null ? o["version"].ToString() : "";
                }
                catch (Exception pex)
                {
                    lock (_auditLock) { _auditCapable = 0; _auditDormantUntil = DateTime.UtcNow.AddMinutes(_auditDbRetryMin); }
                    AiLogStatic("INFO", "AUDITDB", "probe failed, staying dormant " + _auditDbRetryMin
                        + "m: " + pex.Message);
                    return false;
                }
                bool ok = AuditVersionAtLeast(ver, _auditDbMinVer);
                lock (_auditLock)
                {
                    _auditCapable = ok ? 1 : 0;
                    if (!ok) { _auditDormantUntil = DateTime.UtcNow.AddMinutes(_auditDbRetryMin); }
                }
                AiLogStatic("INFO", "AUDITDB", ok
                    ? ("DataAPI " + ver + " supports /api/AI* (min " + _auditDbMinVer + ") -- audit DB active")
                    : ("DataAPI " + ver + " predates /api/AI* (min " + _auditDbMinVer + ") -- audit DB dormant, no calls will be made"));
                return ok;
            }
            catch { return false; }
        }


        // POST that can never throw. null on any failure. Trips the breaker on repeated failure so an
        // absent or sick API cannot cost a round trip on every alert forever.
        internal static JObject AuditPost(string route, JObject body)
        {
            if (!AuditReady() || body == null) { return null; }
            try
            {
                var content = new StringContent(body.ToString(Formatting.None), Encoding.UTF8, "application/json");
                var t = _auditHttp.PostAsync(_auditDbUrl + route, content);
                if (!t.Wait(_auditDbTimeoutMs)) { throw new Exception("timeout"); }
                var resp = t.Result;
                string txt = "";
                try { var rt = resp.Content.ReadAsStringAsync(); rt.Wait(_auditDbTimeoutMs); txt = rt.Result; } catch { }
                if (!resp.IsSuccessStatusCode)
                {
                    // 404 = route absent on this build: treat as FEATURE ABSENT, go dormant quietly.
                    if ((int)resp.StatusCode == 404)
                    {
                        lock (_auditLock) { _auditCapable = 0; _auditDormantUntil = DateTime.UtcNow.AddMinutes(_auditDbRetryMin); }
                        AiLogStatic("INFO", "AUDITDB", "route " + route + " not present on this DataAPI -- dormant");
                        return null;
                    }
                    // v1.0.160.86: LOG THE BODY. The API answers every failure with a detail message
                    // (57 APIErrorMessage.Json sites) naming the column or constraint at fault -- and I
                    // was reading it into txt and discarding it, logging only "HTTP 500". Three rounds
                    // were spent guessing at a cause the server was willing to state outright.
                    AuditNoteFailure(route + " -> HTTP " + (int)resp.StatusCode
                        + (string.IsNullOrEmpty(txt) ? "" : " :: " + Trunc(txt.Replace("\r", " ").Replace("\n", " "), 400)));
                    return null;
                }
                lock (_auditLock) { _auditFails = 0; }
                return string.IsNullOrEmpty(txt) ? new JObject() : JObject.Parse(txt);
            }
            catch (Exception ex) { AuditNoteFailure(route + " -> " + ex.Message); return null; }
        }


        internal static void AuditNoteFailure(string why)
        {
            try
            {
                int n;
                lock (_auditLock) { _auditFails++; n = _auditFails; }
                if (n >= _auditDbMaxFail)
                {
                    lock (_auditLock) { _auditFails = 0; _auditDormantUntil = DateTime.UtcNow.AddMinutes(_auditDbRetryMin); }
                    AiLogStatic("WARN", "AUDITDB", "breaker OPEN for " + _auditDbRetryMin + "m after "
                        + _auditDbMaxFail + " failures; last: " + why);
                }
                else { AiLogStatic("INFO", "AUDITDB", "call failed (" + n + "/" + _auditDbMaxFail + "): " + why); }
            }
            catch { }
        }
    }
}
