using Domain;
using E7MRIWeb.Areas.FRS25.Controllers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace E7.AiCore
{
    // ---- original file header of AiChatController.VerdictCache.cs (kept verbatim) ----
    // <auto-generated-note>
    // AiChatController.VerdictCache.cs -- v1.0.160.79
    // Partial of AiChatController holding the VERDICT CACHE: reuse a stored analysis instead of calling
    // the model again.
    //
    // In its OWN file, not appended to AiAudit.cs, deliberately. AiAudit is PASSIVE -- it records what
    // happened and can fail without changing a verdict. This code is ACTIVE: on a hit it SKIPS the model
    // call entirely. A subsystem that can change what an operator sees deserves to be reasoned about,
    // and reverted, on its own.
    //
    // SAFETY CONTRACT (do not weaken):
    //   * a cached verdict can be WRONG in a way a slow verdict never is -- an alert re-opened later has
    //     new telemetry, and the stored conclusion may no longer be supported. Staleness rules below are
    //     the substance of this file; the lookup is the trivial part;
    //   * ANY failure -- DB dormant, HTTP error, parse error, 404 -- falls through to a normal fresh
    //     analysis. Never an exception, never a blocked verdict;
    //   * a hit is always LABELLED. An operator must never receive a stored answer believing it is new.
    // </auto-generated-note>
    // ---- end of original header ----
    // AnalysisEngine -- VerdictCache.
    // Moved verbatim from AiChatController.VerdictCache.cs in 1.0.165.0 (Shared AI Core 2e);
    // only access modifiers changed (private -> internal). The web app sees internals via InternalsVisibleTo.
    public sealed partial class AnalysisEngine
    {
        // Master switch. Requires AiAuditDbEnabled as well -- there is nothing to read without it.
        internal static readonly bool _cacheEnabled = ReadBool("AiVerdictCacheEnabled", false);

        // An ACTIVE alert is the one whose data keeps moving, so it gets the shorter life.
        internal static readonly int _cacheMaxAgeActiveMin = ClampCfg(ReadInt("AiCacheMaxAgeActiveMin", 15), 1, 1440);

        internal static readonly int _cacheMaxAgeResetMin = ClampCfg(ReadInt("AiCacheMaxAgeResetMin", 60), 1, 10080);

        // v1.0.160.111 CUT G (SL 18): a reset alert's verdict is carried for the life of the AlertId.
        // A NAMED flag, deliberately, rather than setting AiCacheMaxAgeResetMin to its 10080 ceiling
        // -- the intent is then stated, not encoded as a large number a later reader will "tidy up".
        internal static readonly bool _cacheResetNeverExpires = ReadBool("AiCacheResetNeverExpires", true);

        // Compiled safe floor: 1.0.160.106 is the first version with the corrected derived panel.
        // Compared with Version.TryParse -- NEVER string comparison ("1.0.160.99" > "1.0.160.100"
        // as strings). An unparseable CONFIGURED floor falls back to the compiled one and logs.
        internal const string _minAnalysisVersionCompiled = "1.0.160.106";

        internal static readonly Version _minAnalysisVersion = ParseMinAnalysisVersion();

        internal static Version ParseMinAnalysisVersion()
        {
            string raw = ReadStr("MinAcceptableAnalysisVersion", _minAnalysisVersionCompiled);
            Version v;
            if (Version.TryParse(raw, out v)) { return v; }
            Version fallback;
            Version.TryParse(_minAnalysisVersionCompiled, out fallback);
            return fallback;   // never silently disabled
        }

        internal static bool _verFloorFieldWarned;   // v1.0.160.111: log the missing-field case once


        // GET that distinguishes NOT FOUND from BROKEN.
        // This matters: AuditPost treats 404 as "the route does not exist on this DataAPI" and opens
        // the breaker for 10 minutes. But /AIAnalysis/Get returns 404 for an ordinary CACHE MISS --
        // so reusing AuditPost here would let the first miss disable the whole audit subsystem.
        internal static JArray CacheGet(string route)
        {
            if (!AuditReady()) { return null; }
            try
            {
                var t = _auditHttp.GetAsync(_auditDbUrl + route);
                if (!t.Wait(_auditDbTimeoutMs)) { throw new Exception("timeout"); }
                var resp = t.Result;
                if ((int)resp.StatusCode == 404) { return null; }   // MISS -- not a fault, breaker untouched
                if (!resp.IsSuccessStatusCode)
                {
                    AuditNoteFailure(route + " -> HTTP " + (int)resp.StatusCode);
                    return null;
                }
                var rt = resp.Content.ReadAsStringAsync();
                rt.Wait(_auditDbTimeoutMs);
                string txt = rt.Result;
                if (string.IsNullOrEmpty(txt)) { return null; }
                return JArray.Parse(txt);
            }
            catch (Exception ex) { AuditNoteFailure(route + " -> " + ex.Message); return null; }
        }


        // Why this stored row may NOT be reused. Returns null when it IS reusable.
        // Order matters: the cheapest and most decisive checks first.
        // v1.0.160.138: a row that can actually be SERVED. RUNNING and FAILED are not terminal, and
        // a RUNNING row is far more often an orphan than a live run -- nothing closes it if the
        // request never reaches its completion path.
        internal static bool IsTerminalAnalysisRow(JObject row)
        {
            if (row == null) { return false; }
            string st = row["AnalysisStatus"] != null ? row["AnalysisStatus"].ToString() : "";
            bool terminal = string.Equals(st, "COMPLETED", StringComparison.OrdinalIgnoreCase)
                || string.Equals(st, "CACHED", StringComparison.OrdinalIgnoreCase)
                || string.Equals(st, "REANALYSIS", StringComparison.OrdinalIgnoreCase);
            if (!terminal) { return false; }
            // v1.0.160.140: SERVEABLE means terminal AND carrying a verdict. A COMPLETED row with an
            // empty AnalysisOutputJson is just as unusable as a RUNNING one, and it blocked alert
            // 541980 the same way -- the scan skipped the RUNNING row, landed on a payload-less
            // COMPLETED row, and reported "stored row has no verdict payload". Status alone was never
            // the right test; the question is whether there is something to serve.
            return row["AnalysisOutputJson"] != null
                && row["AnalysisOutputJson"].Type != JTokenType.Null
                && row["AnalysisOutputJson"].ToString().Length >= 8;
        }


        internal string CacheStaleReason(JObject row, JObject ctx, bool reRun)
        {
            try
            {
                if (row == null) { return "no row"; }

                // 1. An explicit Re-run is an instruction, not a question.
                if (reRun) { return "operator pressed Re-run"; }

                // 2. Only a COMPLETE analysis can be served. A failed or half-written row has no verdict.
                string st = row["AnalysisStatus"] != null ? row["AnalysisStatus"].ToString() : "";
                // v1.0.160.84: the server writes COMPLETED (and CACHED / REANALYSIS for reuse).
                // I tested for "COMPLETE" here, the same one-letter error 160.83 fixed on the WRITE
                // side -- so the cache would have rejected EVERY valid row and looked broken while
                // the data was fine. Accept all three terminal-success states.
                if (!string.Equals(st, "COMPLETED", StringComparison.OrdinalIgnoreCase)
                    && !string.Equals(st, "CACHED", StringComparison.OrdinalIgnoreCase)
                    && !string.Equals(st, "REANALYSIS", StringComparison.OrdinalIgnoreCase))
                { return "stored analysis is " + (st.Length == 0 ? "incomplete" : st); }
                if (row["AnalysisOutputJson"] == null || row["AnalysisOutputJson"].ToString().Length < 8) { return "stored row has no verdict payload"; }
                // v1.0.160.148: a verdict the UI cannot RENDER must not be served. Rows written before
                // 1.0.160.144 hold only verdict/confidence/category/headline, so they display with
                // "-" for likely cause and action -- and because the cached-serve path copies the
                // served payload into the new row, a thin row REPRODUCED ITSELF on every open and no
                // fresh analysis ever ran to replace it. Refusing it here makes that self-healing:
                // one re-analysis writes a full row and the loop ends without anyone pressing Re-run.
                try
                {
                    JObject _chk = JObject.Parse(row["AnalysisOutputJson"].ToString());
                    JObject _cv = _chk["verdict"] as JObject ?? _chk;
                    bool _hasCause = _cv["likely_cause"] != null && _cv["likely_cause"].ToString().Trim().Length > 0;
                    bool _hasAction = _cv["recommended_action"] != null && _cv["recommended_action"].ToString().Trim().Length > 0;
                    if (!_hasCause && !_hasAction)
                    { return "stored verdict is a summary only (pre-1.0.160.144) -- re-analysing to store a full one"; }
                }
                catch { return "stored payload unparseable"; }

                // 3. The ENGINE must match. On 2026-08-11 quantum11 and deepseek-v4-pro returned
                //    DIFFERENT verdicts for alerts 525605 (80 vs 92) and 525751 (NOT_CONFIRMED vs
                //    CONFIRMED). Serving one for the other would hide a real disagreement between
                //    models behind a cache hit, which is worse than re-running.
                // 3b. v1.0.160.111 CUT G (SL 18): the ANALYSIS CODE may improve. Without this, a
                // verdict produced by 1.0.160.102 -- carrying the derived-panel defect fixed in .106
                // -- would be served forever with its wrong movement numbers. The floor is CONFIG,
                // not "current version": otherwise every deploy would invalidate every stored
                // verdict, which is the opposite of what SL 18 asks for.
                // The audit WRITES this as "ControllerVersion" (AiAudit.cs L329) -- not
                // "ComponentVersion". Reading the wrong name would fail-closed on EVERY row and
                // silently re-analyse everything, defeating SL 18 entirely.
                string rowVerRaw = row["ControllerVersion"] != null ? row["ControllerVersion"].ToString() : "";
                Version rowVer;
                if (!Version.TryParse(rowVerRaw, out rowVer))
                {
                    // Fail CLOSED, but say WHICH case it is. If /AIAnalysis/Get does not project
                    // ControllerVersion at all, every row lands here and nothing is ever served --
                    // that is safe, but it is a CONFIGURATION problem, not a stale verdict, and the
                    // log must make the difference obvious rather than looking like normal churn.
                    if (!_verFloorFieldWarned)
                    {
                        _verFloorFieldWarned = true;
                        AiLog("WARN", "CACHE", "no usable ControllerVersion on the stored row"
                            + (rowVerRaw.Length == 0 ? " (field absent -- check /AIAnalysis/Get projects it)" : " (value '" + rowVerRaw + "')")
                            + " -- every verdict will be re-analysed until this is fixed");
                    }
                    return "stored analysis has no usable controller version";
                }
                if (_minAnalysisVersion != null && rowVer < _minAnalysisVersion)
                { return "stored analysis predates the accepted version floor (" + rowVerRaw + " < " + _minAnalysisVersion + ")"; }

                string rowEngine = row["Engine"] != null ? row["Engine"].ToString() : "";
                string nowEngine = Sess._provider ?? "";
                if (!string.Equals(rowEngine, nowEngine, StringComparison.OrdinalIgnoreCase))
                { return "different engine requested (" + nowEngine + " vs stored " + rowEngine + ")"; }

                // 4. The alert card itself must be unchanged -- new measured values mean a new question.
                string fpNow = AlertFingerprintHex(ctx);
                string fpRow = row["AlertFingerprint"] != null ? row["AlertFingerprint"].ToString() : "";
                fpRow = fpRow.StartsWith("\\x", StringComparison.OrdinalIgnoreCase) ? fpRow.Substring(2) : fpRow;
                if (!string.IsNullOrEmpty(fpNow) && !string.IsNullOrEmpty(fpRow)
                    && !string.Equals(fpNow, fpRow, StringComparison.OrdinalIgnoreCase))
                { return "alert card changed since the stored analysis"; }

                // 5. A reset that arrived AFTER the analysis invalidates it: the stored verdict was
                //    written while the condition was live and may still describe it as active.
                DateTime doneUtc;
                if (row["AnalysisCompletedUtc"] == null
                    || !DateTime.TryParse(row["AnalysisCompletedUtc"].ToString(),
                        System.Globalization.CultureInfo.InvariantCulture,
                        System.Globalization.DateTimeStyles.AdjustToUniversal | System.Globalization.DateTimeStyles.AssumeUniversal,
                        out doneUtc))
                { return "stored completion time unreadable"; }

                DateTime rst;
                string resetRaw = GetCtx(ctx, "resetTime");
                if (resetRaw.Length > 0 && TryParseAlertTime(resetRaw, out rst))
                {
                    if (ToEpochIst(rst) > ToEpochIst(doneUtc.ToLocalTime())) { return "alert reset after the stored analysis"; }
                }

                // 6. Age backstop -- ACTIVE alerts only.
                // v1.0.160.111 CUT G (SL 18): a RESET alert is finished history; its evidence cannot
                // change, and rules 1-5 + 3b already invalidate on every real change (re-run,
                // incomplete row, engine, version floor, card fingerprint, late reset). Expiring it
                // on a timer alone meant the SAME finished alert returned a DIFFERENT verdict
                // tomorrow than today, with nothing to explain why.
                // NOTE: rules 1-5 remain in force for reset alerts. Rule 5 in particular is NOT
                // optional -- an alert analysed while ACTIVE and reset later would otherwise serve
                // its pre-reset verdict forever.
                bool active = resetRaw.Length == 0;
                if (active || !_cacheResetNeverExpires)
                {
                    int maxAge = active ? _cacheMaxAgeActiveMin : _cacheMaxAgeResetMin;
                    double ageMin = (DateTime.UtcNow - doneUtc).TotalMinutes;
                    if (ageMin > maxAge)
                    { return "stored analysis is " + Math.Round(ageMin) + " min old (limit " + maxAge + " for an " + (active ? "active" : "reset") + " alert)"; }
                }

                return null;   // reusable
            }
            catch (Exception ex) { return "staleness check failed: " + ex.Message; }
        }


        // v1.0.160.116 CUT G3: the state the ALERT LIST may display for one stored row.
        //
        // HONEST LIMIT, stated rather than glossed: the list cannot evaluate rule 4 (alert
        // fingerprint) because it has no alert CARD -- only a list row. So this evaluates every rule
        // it CAN (complete row, version floor, engine, reset-after-analysis, and the active-alert age
        // backstop) and the POPUP REMAINS AUTHORITATIVE: opening an alert re-checks all six, so a row
        // shown "valid" may still re-analyse. That is the safe direction -- the list never promises
        // more than the popup delivers, and it NEVER triggers analysis itself.
        //
        // Returns: "valid" | "outdated" | "not_analyzed".
        internal string ListVerdictState(JObject row, string effectiveEngine, string resetTimeRaw)
        {
            try
            {
                if (row == null) { return "not_analyzed"; }

                string st = row["AnalysisStatus"] != null ? row["AnalysisStatus"].ToString() : "";
                if (!string.Equals(st, "COMPLETED", StringComparison.OrdinalIgnoreCase)
                    && !string.Equals(st, "CACHED", StringComparison.OrdinalIgnoreCase)
                    && !string.Equals(st, "REANALYSIS", StringComparison.OrdinalIgnoreCase))
                { return "not_analyzed"; }

                // 3b. version floor -- same rule and same parse as the popup.
                string rowVerRaw = row["ControllerVersion"] != null ? row["ControllerVersion"].ToString() : "";
                Version rowVer;
                if (!Version.TryParse(rowVerRaw, out rowVer)) { return "outdated"; }
                if (_minAnalysisVersion != null && rowVer < _minAnalysisVersion) { return "outdated"; }

                // 3. engine -- compared on the EFFECTIVE internal engine the caller resolved
                // (opaque id -> ResolveEngineAlias -> GateProviderForRole), never on a raw board value.
                if (!string.IsNullOrEmpty(effectiveEngine))
                {
                    string rowEngine = row["Engine"] != null ? row["Engine"].ToString() : "";
                    if (!string.Equals(rowEngine, effectiveEngine, StringComparison.OrdinalIgnoreCase))
                    { return "outdated"; }
                }

                DateTime doneUtc;
                if (row["AnalysisCompletedUtc"] == null
                    || !DateTime.TryParse(row["AnalysisCompletedUtc"].ToString(),
                        System.Globalization.CultureInfo.InvariantCulture,
                        System.Globalization.DateTimeStyles.AdjustToUniversal | System.Globalization.DateTimeStyles.AssumeUniversal,
                        out doneUtc))
                { return "outdated"; }

                // 5. a reset that arrived AFTER the analysis invalidates it -- NOT optional for reset
                // alerts, or an alert analysed while active would show its pre-reset verdict forever.
                bool isReset = !string.IsNullOrEmpty(resetTimeRaw);
                if (isReset)
                {
                    DateTime rst;
                    if (TryParseAlertTime(resetTimeRaw, out rst)
                        && ToEpochIst(rst) > ToEpochIst(doneUtc.ToLocalTime()))
                    { return "outdated"; }
                }

                // 6. age backstop -- ACTIVE alerts only (SL 18: a reset alert is finished history).
                if (!isReset || !_cacheResetNeverExpires)
                {
                    int maxAge = !isReset ? _cacheMaxAgeActiveMin : _cacheMaxAgeResetMin;
                    if ((DateTime.UtcNow - doneUtc).TotalMinutes > maxAge) { return "outdated"; }
                }
                return "valid";
            }
            catch { return "not_analyzed"; }   // never fail loudly on a list render
        }


        // Batch lookup for the board. ONE call per alert id, but bounded and display-only.
        // NEVER triggers analysis.
        internal JObject ListVerdictStates(List<long> alertIds, string requestedEngineOpaque, bool siteKeep)
        {
            JObject outp = new JObject();
            if (alertIds == null || alertIds.Count == 0) { return outp; }
            // Resolve the board's OPAQUE id through the same path a verdict request uses, so the
            // comparison is against the effective INTERNAL engine, not a raw client value.
            string effective = GateProviderForRole(ResolveEngineAlias(requestedEngineOpaque), siteKeep);
            for (int i = 0; i < alertIds.Count; i++)
            {
                long id = alertIds[i];
                string state = "not_analyzed";
                try
                {
                    JArray rows = CacheGet("/api/AIAnalysis/Get?AlertId=" + id);
                    if (rows != null && rows.Count > 0)
                    {
                        JObject row = rows[0] as JObject;
                        string resetRaw = (row != null && row["ResetTime"] != null) ? row["ResetTime"].ToString() : "";
                        state = ListVerdictState(row, effective, resetRaw);
                    }
                }
                catch { state = "not_analyzed"; }
                outp[id.ToString()] = state;
            }
            return outp;
        }


        // Returns the stored verdict envelope to serve, or null to analyse normally.
        // Null is ALWAYS the safe answer and is what every failure path returns.
        internal JObject TryServeFromCache(JObject ctx, bool reRun)
        {
            Sess._servedFromCache = false;
            try
            {
                if (!_cacheEnabled || !_auditDbEnabled) { return null; }
                long alertId = CtxLong(ctx, "alertId");
                if (alertId <= 0) { return null; }

                // IncludeJson=1 is REQUIRED: AnalysisOutputJson is a "heavy" column and the server
                // strips it from GET responses without it -- the cache would find a row with the
                // verdict removed and serve nothing.
                JArray rows = CacheGet("/api/AIAnalysis/Get?AlertId=" + alertId + "&IncludeJson=1");
                if (rows == null || rows.Count == 0) { return null; }
                // v1.0.160.138: newest TERMINAL row, not simply rows[0]. A row left RUNNING -- by a
                // client that closed the popup mid-run, or by the cached-serve path that opens an
                // audit row and returns without completing it -- sits at the top of this list forever
                // and blocks the cache for that alert PERMANENTLY. Alert 541980 had been analysed
                // many times and still re-ran on every open, reporting "stored analysis is RUNNING".
                // One orphan poisoned every later lookup.
                JObject row = rows[0] as JObject;
                if (!IsTerminalAnalysisRow(row))
                {
                    for (int i = 1; i < rows.Count; i++)
                    {
                        JObject cand = rows[i] as JObject;
                        if (IsTerminalAnalysisRow(cand))
                        {
                            row = cand;
                            AiLog("INFO", "CACHE", "alert " + alertId + ": newest row is non-terminal; using the newest completed row instead");
                            break;
                        }
                    }
                }

                string why = CacheStaleReason(row, ctx, reRun);
                if (why != null)
                {
                    long rid = 0;
                    if (row != null && row["AnalysisId"] != null) { long.TryParse(row["AnalysisId"].ToString(), out rid); }
                    // Mark it stale ONLY for reasons that make the row permanently wrong. A Re-run or
                    // an engine switch says nothing about the stored row's validity for its own
                    // engine -- marking those stale would throw away a good analysis.
                    bool permanent = why.StartsWith("alert card changed") || why.StartsWith("alert reset");
                    if (permanent && rid > 0)
                    {
                        JObject sb = new JObject();
                        sb["AnalysisId"] = rid;
                        sb["StaleReason"] = PgSafe(why, 128);
                        System.Threading.Tasks.Task.Run(() => { try { AuditPost("/api/AIAnalysis/Stale", sb); } catch { } });
                    }
                    AiLog("INFO", "CACHE", "miss for alert " + alertId + ": " + why);
                    return null;
                }

                JObject env;
                try { env = JObject.Parse(row["AnalysisOutputJson"].ToString()); }
                catch (Exception pex)
                {
                    AiLog("WARN", "CACHE", "stored payload unparseable for alert " + alertId + ": " + pex.Message);
                    return null;
                }

                // v1.0.160.153: REFUSE degraded rows (analysed while the E7 API was failing --
                // envelopes/FRS/rangeHist all 403). Same policy as the .148 thin-verdict
                // refusal: a stored answer produced from starved inputs must not be replayed
                // as authoritative; one healthy re-analysis replaces it. While the outage
                // persists every open re-analyses -- accepted: honest current state over a
                // cheap wrong answer. (541980: degraded row NOT_CONFIRMED 72; healthy re-run
                // CONFIRMED 82.)
                try
                {
                    JObject dvv = env["verdict"] as JObject ?? env;
                    JToken dg = dvv["degraded_inputs"];
                    if (dg != null && dg.Type == JTokenType.Boolean && (bool)dg)
                    {
                        AiLog("INFO", "CACHE", "miss for alert " + alertId
                            + ": stored analysis ran with degraded inputs (E7 API failure) -- re-analysing");
                        return null;
                    }
                }
                catch { }

                long id2 = 0;
                if (row["AnalysisId"] != null) { long.TryParse(row["AnalysisId"].ToString(), out id2); }
                if (id2 > 0)
                {
                    JObject sv = new JObject();
                    sv["AnalysisId"] = id2;
                    // v1.0.160.85: captured before the first await -- reading LoginUser here returns
                    // null, because ConfigureAwait(false) has already dropped HttpContext.Current.
                    string who = Sess._luName ?? "";
                    sv["LastServedTo"] = who.Length > 0 ? who : "ENERGY7";
                    System.Threading.Tasks.Task.Run(() => { try { AuditPost("/api/AIAnalysis/Served", sv); } catch { } });
                }

                // LABEL IT. An operator must never receive a stored answer believing it is new.
                try
                {
                    JObject v = env["verdict"] as JObject ?? env;
                    // v1.0.160.153: emit ISO. Raw ToString() is locale-formatted
                    // ("8/15/2026 8:47:35 PM") and the view truncates cached_at at 16 chars
                    // assuming ISO -- which printed "8/15/2026 8:47:3". (AnalysisCompletedUtc
                    // carries IST wall-clock despite the name -- recorded, not changed here.)
                    string doneAt = "";
                    if (row["AnalysisCompletedUtc"] != null)
                    {
                        string doneRaw = row["AnalysisCompletedUtc"].ToString();
                        DateTime doneDt;
                        doneAt = DateTime.TryParse(doneRaw, out doneDt)
                            ? doneDt.ToString("yyyy-MM-ddTHH:mm:ss")
                            : doneRaw;
                    }
                    v["served_from_cache"] = true;
                    v["cached_at"] = doneAt;
                    // v1.0.160.155: cached_engine REMOVED entirely (owner: "model never
                    // display -- just cache/fresh"). .153 gated it to site-keeping; now no
                    // session receives vendor identity on the badge. Engine/ModelId remain on
                    // the audit rows and in the 7W audit block for traceability. The matching
                    // view segment is removed in 1.0.55.104 -- required regardless of this
                    // change, because CACHED rows stored before .155 still carry cached_engine
                    // inside their copied payload.
                    v["cache_note"] = "Previous analysis reused -- no new model call. Press Re-run for a fresh analysis.";
                }
                catch { }

                Sess._servedFromCache = true;
                AiLog("INFO", "CACHE", "HIT for alert " + alertId + " -> analysis " + id2 + " reused (no model call)");
                return env;
            }
            catch (Exception ex)
            {
                AiLog("INFO", "CACHE", "lookup failed, analysing normally: " + ex.Message);
                return null;
            }
        }
    }
}
