// <auto-generated>
// v1.0.160.50 -- CIRCUIT TOPOLOGY + UPSTREAM CAUSALITY.
// Built from the owner-supplied wisdom files (track current/voltage flow, signal, point machine).
// STRUCTURE AND RELATIONSHIPS ONLY -- the example figures in those files are one snapshot and vary
// by circuit, hardware, ballast, weather and load, so no numeric value from them is reproduced here
// as a threshold. ASCII-only and older-C# compatible.
// Supplements, never replaces, CauseLogicMaps/RdpmsMaps, approved site plans, control tables,
// equipment manuals, schedules, or authorized field procedure.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Text;

namespace E7.AiCore
{
    // One invariant of a circuit: an arithmetic relationship that must hold between measured
    // attributes, plus what a violation of it MEANS diagnostically.
    public sealed class CircuitInvariant
    {
        public readonly string Id, Family, Relation, Meaning, Violation;
        public CircuitInvariant(string id, string family, string relation, string meaning, string violation)
        { Id = id; Family = family; Relation = relation; Meaning = meaning; Violation = violation; }
    }

    public static class CircuitWisdom
    {
        public const string Version = "1.0.0";
        public const string BuiltOn = "2026-08-10";

        public const string SafetyContract =
            "ADVISORY ONLY. The approved FRS cause logic, CauseLogicMaps/RdpmsMaps, thresholds and health bands remain " +
            "authoritative; where this reference and the maps differ, the maps win. Never operate, bypass, reset or " +
            "certify signalling gear from AI advice.";

        // The rule the owner stated: every value has an upstream driver, so a downstream value
        // cannot move unless something upstream moved.
        public const string CausalityRule =
            "UPSTREAM CAUSALITY (apply to every claimed change):\n" +
            "  Every measured value has an UPSTREAM DRIVER. A downstream value cannot move unless something upstream\n" +
            "  of it moved. So for any change you are asked to judge, exactly one of these is true:\n" +
            "   (a) an upstream driver ALSO moved -> the change is REAL, and the upstream mover NAMES THE CAUSE; or\n" +
            "   (b) nothing upstream moved -> the change is a COMPUTATION or SENSOR artifact, not degradation.\n" +
            "  State which of (a) or (b) you concluded, and name the upstream attribute you checked.\n" +
            "  CRITICAL EXCEPTION -- do NOT misread change-of-value sampling: under deadband sampling an attribute that\n" +
            "  has NOT changed is HELD at its last value, and that held value IS its value at the incidence. A HELD\n" +
            "  upstream is a real measured value, not a missing one. Case (b) means the upstream genuinely did not\n" +
            "  move while the downstream did -- it does NOT mean the upstream simply has no fresh sample.\n" +
            "  Never use this rule alone to overturn a card-confirmed threshold breach.";

        public static readonly CircuitInvariant[] Invariants = new CircuitInvariant[]
        {
            new CircuitInvariant("K1", "Track Circuit",
                "ITC TFC O/P = ITC BATT CHARG + ITC FEED END",
                "The charger output SPLITS: part charges the battery, part is drawn as track feed.",
                "If the three do not add up, suspect a charger/battery-bus measurement rather than the track."),

            new CircuitInvariant("K2", "Track Circuit",
                "ITC FEED END = ITC RELAY END + IBALST",
                "Feed current = what reaches the relay coil + what the ballast/sleepers steal on the way. " +
                "THIS IS THE KEY DISCRIMINATOR: if ITC RELAY END falls while ITC FEED END HOLDS, the difference is " +
                "leakage rising -> BALLAST / GLUED-JOINT problem. If ITC FEED END and ITC RELAY END fall TOGETHER, " +
                "leakage is unchanged -> a FEED-SIDE / SUPPLY problem, NOT leakage.",
                "IBALST can NEVER be negative -- ballast only steals current, so ITC RELAY END can never exceed " +
                "ITC FEED END. A negative IBALST is a MEASUREMENT fault (multiplication factor, swapped If/Ir " +
                "channel, wrong tag binding), NOT a track fault -- never raise a leakage conclusion from it. A " +
                "small negative within sensor tolerance is a calibration offset. Likewise a relay-end drop with " +
                "no feed-end movement and no IBALST rise is arithmetically impossible -- re-check the sensors."),

            new CircuitInvariant("K3", "Track Circuit",
                "VTC FEED END = VTC TFC O/P - VTC VAR RES - VTC CH FEED END",
                "Rail voltage is the charger output MINUS the series drops (regulating variable resistance, choke/feed leg).",
                "A rail-voltage fall with the charger output steady means a SERIES DROP grew (VAR RES / choke / connections), " +
                "not a charger fault."),

            new CircuitInvariant("K4", "Track Circuit",
                "Relay-end VOLTS and relay-end CURRENT move together through the coil (Vr with ITC RELAY END)",
                "A DIRECTION rule on MEASURED sensors. Do not test it as an equality: TR V (attribute 571) is " +
                "DERIVED in this deployment as Ir x R737 (attribute 737, Track Relay resistance), so comparing " +
                "TR V against R737 x Ir compares a value with itself and can never disagree. Vr (attribute 3) IS " +
                "a real sensor, but it sits at a different point in the circuit and its offset from R737 x Ir " +
                "varies per asset, so only the DIRECTION of movement is reliable.",
                "Relay current moving materially while relay volts do NOT (or moving the opposite way) means the " +
                "two contradict each other: suspect a SENSOR/WIRING fault on one of them, not degradation."),

            new CircuitInvariant("K5", "Track Circuit",
                "The BATTERY feeds the track; the charger keeps the battery charged",
                "The track feed is drawn from the battery, not directly from the charger. This is why the track rides " +
                "through an AC/charger failure.",
                "Do NOT attribute a track-current fall to an AC/charger event on its own -- ride-through means the " +
                "track survives it. Require a battery-bus or feed-side movement before blaming the supply."),

            new CircuitInvariant("K6", "Track Circuit",
                "Relay UP means healthy-and-clear; relay DOWN means occupied OR faulty",
                "Fail-safe asymmetry: a train axle shorting the rails, a broken rail, a cut cable, power loss or " +
                "flooded ballast all produce the SAME DOWN state.",
                "Never read DOWN as proof of a fault, nor as proof of a train. Resolve it with the other evidence."),

            new CircuitInvariant("S1", "Signal",
                "Cascade is one-way: DG (Green) -> HHG (Double Yellow) -> HG (Yellow) -> RG (Red)",
                "On lamp failure the aspect steps DOWN to a more restrictive one, never up. DPR/HHPR/HPR are the " +
                "cutting/proving relays; there is NO RPR because Red is the bottom of the cascade.",
                "A displayed aspect MORE PERMISSIVE than commanded is a WRONG-SIDE FAILURE -- the most serious flag."),

            new CircuitInvariant("S2", "Signal",
                "Lit means BOTH high together: ISIG (current) AND VSIG (voltage)",
                "Exactly one lamp is lit at a time, and exactly one ECR (RECR/DECR/HECR/HHECR) is picked up, matching " +
                "the lit lamp.",
                "VSIG high with ISIG ~0 = broken filament / open lamp. ISIG high with VSIG ~0 = sensor/wiring fault. " +
                "Two lamps lit, or an ECR not matching the lit lamp, is a fault. IGNORE small off-lamp residual " +
                "currents -- they carry no functional meaning."),

            new CircuitInvariant("S3", "Signal",
                "A sag across ALL lamps is a supply problem, not a lamp problem",
                "Lit-lamp VSIG sits near the 110 V AC band; PR/ECR relay voltages sit in a stable ~24 V DC band.",
                "One lamp low = that lamp/its feed. All lamps low = the 110 V AC lamp supply."),

            new CircuitInvariant("P1", "Point Machine",
                "The vital output is DETECTION / CORRESPONDENCE, not motion",
                "A throw is Throw -> Lock -> Detect. The point is proved only when detection agrees with the commanded " +
                "position at BOTH A and B ends.",
                "'Proved' is a strong statement of health; 'not proved' is AMBIGUOUS (in transit OR faulty). " +
                "Respect that asymmetry -- never read not-proved as proof of a fault."),

            new CircuitInvariant("P2", "Point Machine",
                "Operation signature: peak current = breakaway/lock, average current = running friction, TPT = duration",
                "High peak with normal avg/time = breakaway or locking issue. Normal peak with high avg+time = sustained " +
                "friction/lubrication. High peak AND avg AND time together = real obstruction. Voltage dipping while " +
                "current is high = SUPPLY limitation, not mechanics.",
                "A-end vs B-end divergence means one machine is working harder -- adjustment or drive fault."),

            new CircuitInvariant("P3", "Point Machine",
                "During a throw BOTH NWKR and RWKR are down -- that is normal, not a fault",
                "The out-of-correspondence window is where the operation signature lives.",
                "Correspondence NEVER restored after the throw IS a vital failure (not thrown/locked, detection fault, " +
                "or A/B disagreement)."),

            new CircuitInvariant("X1", "",
                "Cross-device values are only comparable on TIME-ALIGNED samples",
                "Feed end, relay end, location box and relay room each have their own IoT device and clock. During a " +
                "state change (1-2 s) a small skew can make a combined picture look incoherent while every sensor is healthy.",
                "Check per-device freshness before treating an incoherence as a fault."),
        };

        // Retrieval: the family's invariants + the shared cross-device caveat.
        public static string BuildPrompt(string family, int maxRules)
        {
            if (maxRules < 1) { maxRules = 1; }
            StringBuilder b = new StringBuilder();
            int n = 0;
            for (int pass = 0; pass < 2 && n < maxRules; pass++)
            {
                for (int i = 0; i < Invariants.Length && n < maxRules; i++)
                {
                    CircuitInvariant r = Invariants[i];
                    bool famMatch = !string.IsNullOrEmpty(r.Family)
                        && !string.IsNullOrEmpty(family)
                        && string.Equals(r.Family, family, StringComparison.OrdinalIgnoreCase);
                    bool shared = string.IsNullOrEmpty(r.Family);
                    if ((pass == 0 && !famMatch) || (pass == 1 && !shared)) { continue; }
                    b.Append("- [").Append(r.Id).Append("] ").Append(r.Relation).Append("\n");
                    b.Append("    means: ").Append(r.Meaning).Append("\n");
                    if (!string.IsNullOrEmpty(r.Violation)) { b.Append("    if violated: ").Append(r.Violation).Append("\n"); }
                    n++;
                }
            }
            if (n == 0) { return ""; }
            return b.ToString();
        }
    }
}
